Qrf orbital
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #144
Opened 2024-03-29 01:49 UTC by wersal454

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:

OKAY. This is kinda huge. Initial draft or whatever. A lot to do(wright code and test). I believe I created all necessary files, but I'm no expert on supports and especially QRFs.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:
Added some notes in fn_orbitalLanding on how qrf should behave. Maybe in the future include Orbital vehicle drop?

2024-03-29 01:54 UTC, wersal454 commented
Almost forgot. After testing we need to move this QRF in "futuristic" option and move Orbital beam to something like "futuristic-unfair". Of course, this option will need to be added to the menu, but I don't think it would be too difficult to do.

2024-03-29 15:30 UTC, SilenceIsFatto commented
This is a continuation of #126

2024-07-15 11:54 UTC, wersal454 commented
Star wars modset needs droppods added (I think CIS has droppods(either as a propper vehicle or as scenery object)
Should probably add droppods(space capsule since it's in vanilla) to every modern modset (just in case someone wants ai to use orbital qrf with rhs or something)
Need to figure out what to do with single seater pods (currently they are launching way to long from one another due to crashingeffect function checking and waiting for altitude of 2m or so, maybe use eventhandlers?) + add bomb explosion before touchdown (might need to look at how Rivals carbomb is doing that)
Need to add a parametr, futuristic-unfair and move current orbital laser there and orbital qrf into just futuristic

2024-07-15 11:57 UTC, stutpip123 commented
would need to be enabled/disabled by the "futuristic supports" parameter if included in modern

2024-07-15 22:35 UTC, SilenceIsFatto requested changes
What happens if a template doesn't have a `vehiclesDropPod`?

2024-07-15 22:35 UTC, SilenceIsFatto commented on A3A/addons/core/functions/AI/fn_orbitalLanding.sqf
How much of the TODO is still needed?

Also the code just generally needs to be formatted better:

Whitespace is both free and infinite - don't make the code hard to read when it is so simple to make it easier to read.

- Always have a space before and after an else statement.
```sqf
} else {
```

- Instead of doing `if (condition) then {/*do nothing*/} else {/*do something*/}`, adopt the strategy of either exiting early (if applicable), or just change your statement. For example, L42 - L71:
```sqf 
if (_podseats == 1) then {

}else{
	_pod allowDamage false;

	_pod lock 2;
	_pod setVehicleLock "LOCKED";
	_pod setPos [(_landpos select 0),(_landpos select 1), 3000];
	_pod setVelocity [0,0,-150];
	[_pod] call SCRT_fnc_effect_orbitalDropEffect;
	_pod setVelocity [0,0,-1];
	_bomb = "DemoCharge_Remote_Ammo_Scripted" createVehicle [0,0,0];
	_bomb setPosWorld (position _pod); 
	_bomb setDamage 1;
	sleep 0.2;
	_pod setPos [(getPos _pod select 0),(getPos _pod  select 1),1];

	sleep 1;

	{
		_x allowDamage true;

	} forEach units _groupX;

	_pod allowDamage true;

	_pod animateDoor ['door_R', 1];
	_pod animateDoor ["Door_rear_source", 1, true];
	[_pod] call A3A_fnc_smokeCoverAuto;
};
```
You could just do:
```sqf
if (_podseats != 1) then {
  // do something
};
```

2024-07-15 22:35 UTC, SilenceIsFatto commented on A3A/addons/core/functions/AI/fn_orbitalLandingSinglePod.sqf
> +_x leaveVehicle _podX;
```suggestion
params ["_podX", "_pod", "_dist", "_x", "_positionX", "_posOrigin"];

_podX allowDamage false;
_podX lock 2;
_podX setVehicleLock "LOCKED";

_landPos = _positionX getPos [_dist,random 360];

_podX = typeOf _pod createVehicle position _x;
_podX setPos [((_landpos select 0) + random 30),((_landpos select 1) - random 30), 3000];
_podX setVelocity [0,0,-135];
_podX lock 2;
_podX setVehicleLock "LOCKED";

_x moveInAny _podX;

[_podX] call SCRT_fnc_effect_orbitalDropEffect;
_podX setVelocity [0,0,-1];

_bomb = "DemoCharge_Remote_Ammo_Scripted" createVehicle [0,0,0];
_bomb setPosWorld (position _podX); 
_bomb setDamage 1;

sleep 0.05;

_podX setPos [(getPos _podX select 0),(getPos _podX  select 1),0.5];
_podX allowDamage true;

_x allowDamage true;

sleep 1.75;

_x action ["Eject", _podX];
_x leaveVehicle _podX;
```

2024-07-15 22:46 UTC, wersal454 commented
> What happens if a template doesn't have a `vehiclesDropPod`?

Yep, forgot about that one, might check how absence of helicopters is handled

2024-07-15 22:48 UTC, wersal454 commented on A3A/addons/core/functions/AI/fn_orbitalLanding.sqf
> How much of the TODO is still needed?
Not much
Clean up, and a way to prevent it shitting the bed once no droppod is found

2024-07-15 22:52 UTC, wersal454 commented on A3A/addons/core/functions/AI/fn_orbitalLanding.sqf
and some balancing may be required, but that would require some proper testing

2024-07-25 17:52 UTC, wersal454 commented
Just realized, I should probably add stuff like blowing door panel on ODST pod, or opening the doors on other pods. Just stuff like that

2024-07-31 13:07 UTC, SilenceIsFatto reviewed
Generally you just need to clean up commented out code that isn't needed, and properly fill out function headers so their args and such are correct

2024-07-31 13:07 UTC, SilenceIsFatto commented on A3A/addons/core/functions/CREATE/fn_createAttackForceMixed.sqf
> +    if (typeOf _vehicleType == "vehiclesDropPod") then {
Does _vehicleType exist in this context?

Also are you sure you should be comparing to a literal string? Shouldn't you be comparing to `FACTION get "vehiclesDropPod"`

2024-07-31 13:07 UTC, SilenceIsFatto commented on A3A/addons/core/functions/CREATE/fn_createAttackForceMixed.sqf
> +    }else{
```suggestion
    } else {
```

2024-07-31 13:07 UTC, SilenceIsFatto commented on A3A/addons/core/functions/CREATE/fn_createAttackForceOrbital.sqf
Change the header to match what this fnc actually does

2024-08-09 19:40 UTC, SilenceIsFatto requested changes
It'd be smart to double check all of the "get" and swap them to getOrDefault given the issues we had with it last release

2024-08-09 19:40 UTC, SilenceIsFatto commented
Just the `get "vehiclesDropPod"`, etc*

2024-08-13 12:36 UTC, wersal454 commented
> It'd be smart to double check all of the "get" and swap them to getOrDefault given the issues we had with it last release

I think there is no need for that since there is a droppod in faction defaults, thought I think we need to check the crashsite mission check for droppod, I don't think it will spawn satellite version of the mission if there is no droppod in the template since we doing getordefault check

2024-08-16 13:02 UTC, SilenceIsFatto requested changes
Make sure to remove commented out segments of code that are no longer needed, makes it unnecessarily hard to read

2024-08-16 13:02 UTC, Silence-112 commented on A3A/addons/core/functions/Missions/fn_LOG_Crashsite.sqf
> +sleep 60; ///prep time
```suggestion
private _missionStart = serverTime;
waitUntil {
    sleep 60;
    (call SCRT_fnc_misc_getRebelPlayers) inAreaArray [_crashPosition, 1500, 1500] isNotEqualTo [] || {_missionStart >= serverTime + 600 }
};
sleep 60; ///prep time

```

2024-08-16 13:02 UTC, Silence-112 commented on A3A/addons/core/functions/Missions/fn_LOG_Crashsite.sqf
> +Info("Helicrash clean up complete.");
```suggestion
Info("Crashsite clean up complete.");
```

2024-08-16 13:02 UTC, Silence-112 commented on A3A/addons/core/functions/Missions/fn_LOG_Crashsite_Satellite.sqf
>  private _missionstart = serverTime;
```suggestion
private _missionStart = serverTime;
```

2024-08-16 13:02 UTC, Silence-112 commented on A3A/addons/core/functions/Missions/fn_LOG_Crashsite_Satellite.sqf
> +    (call SCRT_fnc_misc_getRebelPlayers) inAreaArray [_crashPosition, 1500, 1500] isNotEqualTo [] || {_missionstart >= serverTime + 600 }
```suggestion
    (call SCRT_fnc_misc_getRebelPlayers) inAreaArray [_crashPosition, 1500, 1500] isNotEqualTo [] || {_missionStart >= serverTime + 600 }
```

2024-08-16 13:02 UTC, Silence-112 commented on A3A/addons/core/functions/Missions/fn_LOG_Crashsite_Satellite.sqf
I rewrote a lot of the original crashsite mission, does this function have those changes?

2024-08-16 13:02 UTC, Silence-112 commented on A3A/addons/core/functions/CREATE/fn_cargoSeats.sqf
> +if (_veh in (_faction get "vehiclesPolice")) then { _cargoSeats = 6 min _cargoSeats };
Any particular reason this was changed?

2024-08-16 13:02 UTC, Silence-112 commented on A3A/addons/core/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
> +        if (typeOf _vehicle in (_faction get "vehiclesDropPod") ) exitwith {
```suggestion
        if (typeOf _vehicle in (_faction get "vehiclesDropPod") ) exitWith {
```

2024-08-16 13:02 UTC, Silence-112 commented on A3A/addons/core/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
> +            [_vehicle, _cargoGroup, _posDestination, _posOrigin/* , _crewGroup */] spawn A3A_fnc_OrbitalLanding;
```suggestion
            [_vehicle, _cargoGroup, _posDestination, _posOrigin] spawn A3A_fnc_OrbitalLanding; // , _crewGroup
```

2024-08-16 13:02 UTC, Silence-112 commented on A3A/addons/scrt/CfgSounds.hpp
> +    class fire
Does this `class fire` not break things?

2024-08-16 13:02 UTC, Silence-112 commented on A3A/addons/core/functions/CREATE/fn_createAttackForceOrbital.sqf
> +    _isTransport = _vehAttackCount == 0 or (_numTransports / _i) < _transportRatio;
```suggestion
    _isTransport = ((_vehAttackCount == 0) || {(_numTransports / _i) < _transportRatio)});

```

2024-08-16 14:58 UTC, wersal454 commented on A3A/addons/core/functions/CREATE/fn_cargoSeats.sqf
> +if (_veh in (_faction get "vehiclesPolice")) then { _cargoSeats = 6 min _cargoSeats };
To allow Police to spawn inside vehicles with more than 4 seats? Or to spawn at least 6 police guys if amount of seats allow it? Don't honestly remember

2024-08-16 14:59 UTC, wersal454 commented on A3A/addons/scrt/CfgSounds.hpp
> +    class fire
Ehhh, need to check that, but I don't think so, don't remember any errors involving that

2024-08-22 10:53 UTC, wersal454 commented on A3A/addons/core/functions/Missions/fn_LOG_Crashsite_Satellite.sqf
22 lines less in this mission variant, need to check that.

2024-08-27 12:04 UTC, Silence-112 approved these changes
Ready for testing I think

2024-09-25 13:51 UTC, merged