Split vanilla store + additions + kkiv 2035 mod support
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #150
Opened 2024-03-31 04:27 UTC by wersal454

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:

Splitted vanilla store into dlcs + added some stuff
Added support for kkiv 2035 mod    

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
enable dlcs(?)
load mod
go to blackmarket guy and check the store

2024-04-08 21:16 UTC, SilenceIsFatto commented
I don't mind the kkiv 2035 mod support/additions part of this PR, but the Split vanilla store part is a no-go. It's pointless and will bloat the store far too much. 

Perhaps it might be better to close this PR and open a new one with just the additions?

2024-04-08 21:25 UTC, wersal454 commented
nuh, honestly I think problem is how categories are displayed in the store. I've looked at store ui, haven't figured out how to change listbox placement, but I will look into it, because now it's kinda junky

2024-04-08 21:32 UTC, SilenceIsFatto commented
At the very least do it in a separate PR

2024-05-06 15:31 UTC, SilenceIsFatto requested changes
There's 2 missing categories (not sure which cfg they belong to)

May also be worth adding a "spacer" category, so that modsets have a single space between them. E.g:

```
Apex SMGs
Apex Snipers
\\ ======= // - empty spacer category
Art Of War Misc
\\ ======= // - empty spacer category
Etc
```

2024-05-06 15:31 UTC, Silence-112 commented on A3A/addons/hals/Addons/store/config/contact.hpp
> +			ITEM(G_Blindfold_01_whitw_F, 200, MISC_STOCK);
```suggestion
			ITEM(G_Blindfold_01_white_F, 200, MISC_STOCK);

```

2024-05-07 01:16 UTC, wersal454 commented
> There's 2 missing categories (not sure which cfg they belong to)
> 
> May also be worth adding a "spacer" category, so that modsets have a single space between them. E.g:
> 
> ```
> Apex SMGs
> Apex Snipers
> \\ ======= // - empty spacer category
> Art Of War Misc
> \\ ======= // - empty spacer category
> Etc
> ```

Fixed it, I like idea with spacers though I have no idea how it could be done, if you know do a suggestion and I look into it

2024-05-07 12:51 UTC, SilenceIsFatto commented
Spacers would have to be done via the function that initialises the trader categories, i'll look into that but there is a bigger issue currently

All of this stuff will still be added to the store even if you have mods loaded (previously if you had mods loaded, it would not add any vanilla stuff unless you explicitly enabled the param to do so)

We still want it to be that way, so will need to figure something out

2024-05-07 13:04 UTC, SilenceIsFatto requested changes

2024-05-07 13:04 UTC, SilenceIsFatto commented on A3A/addons/ultimate/config/trader/cfgTraderMods.hpp
> +    };
```suggestion
```

2024-05-07 13:04 UTC, Silence-112 commented on A3A/addons/ultimate/config/trader/cfgTraderMods.hpp
> +    };
I pushed a commit, so that suggestion won't make much sense without reading it

2024-05-07 14:22 UTC, SilenceIsFatto commented
Seems like too much work to get proper spacers to work, so this will do fine

2024-05-07 14:24 UTC, SilenceIsFatto approved these changes

2024-05-07 14:25 UTC, merged