Remnants
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #196
Opened 2024-05-05 15:38 UTC by wersal454

## What type of PR is this?
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:

New vanilla Rival faction

Remnants - remnants of the AAF forces sponsored by CSAT, who want to regain control of the islands.

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:
can use new [[], "SCRT_fnc_rivals_encounter_OccVsRivalsSkirmish"] call A3A_fnc_scheduler; command to spawn rivals vs occ skirmish
********************************************************

2024-05-05 18:20 UTC, wersal454 commented
big thanks to @UAC-MaxxLite for the custom flag

2024-05-09 14:30 UTC, SilenceIsFatto requested changes

2024-05-09 14:30 UTC, SilenceIsFatto commented on A3A/addons/core/CfgMarkers.hpp
> +		name = "AAF remnants";
```suggestion
		name = "AAF Remnants";
```

2024-05-09 14:30 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates.hpp
> +        name = "A3 Remnants";
```suggestion
        name = "A3 AAF Remnants";
```

2024-05-09 14:30 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Riv_Exegermenos.sqf
>  } ;
```suggestion
};
```

2024-05-09 14:30 UTC, SilenceIsFatto commented on A3A/addons/scrt/Stringtable.xml
> +                <Original>Remnants.\nRemnants of the AAF forces sponsored by CSAT, who want to regain control of the islands..</Original>
```suggestion
                <Original>Remnants.\nRemnants of the AAF forces sponsored by CSAT, who want to regain control of the islands.</Original>
```

2024-05-09 14:30 UTC, SilenceIsFatto commented on A3A/addons/scrt/Stringtable.xml
> +                <French>Remnants.\nPLACEHOLDER.</French>
Might aswell just remove these translations so it uses english, unless somebody gives a translation

2024-05-09 14:31 UTC, SilenceIsFatto commented on A3A/addons/scrt/Stringtable.xml
> +                <French>Remnants.\nPLACEHOLDER.</French>
Ignore the russian one, didn't realise I selected it

2024-05-09 14:40 UTC, SilenceIsFatto approved these changes

2024-05-09 14:42 UTC, merged