Display self-revive cooldown in unconscious state
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #246
Opened 2024-07-12 15:10 UTC by blackwaterbread

## What type of PR is this?
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:

We need a UI that tells us how long we have left to cooldown Self-Revive when in unconscious.

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

Makes the player in unconscious, and verify that the cooldown UI is displayed in the top right corner.

********************************************************
Notes:

2024-07-12 22:55 UTC, SilenceIsFatto requested changes
Make sure to read the suggestion. Other than that, looks fine

2024-07-12 22:55 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Revive/fn_unconscious.sqf
> +	private _diff = (player getVariable ["A3A_selfReviveTimeout", -1]) - time;
```suggestion
	private _diff = (_unit getVariable ["A3A_selfReviveTimeout", -1]) - time;
```

Use the _unit variable for consistency

2024-07-13 13:34 UTC, SilenceIsFatto reviewed
The hint doesn't disappear when you hit R to respawn and the cooldown keeps ticking even after respawning. Is that intended behaviour?

Using withstand does seem to hide the hint as usual, that or it gets overwritten by the antistasi hint.

You should probably be using the `A3A_fnc_customHint` function instead of `hintSilent` as using normal hints can cause them to be overwritten without any chance to read them.

2024-07-13 14:24 UTC, blackwaterbread commented
Thank you for your detailed review. Working on it based on your suggestions.

2024-07-13 20:35 UTC, SilenceIsFatto reviewed
Make sure to pass a silent notification argument to the customHint call, else you'll be spamming people with sounds

Other than that, it seems fine now

2024-07-14 13:08 UTC, SilenceIsFatto approved these changes
Looks good to me, will need to be tested by us before merge

2024-07-14 13:16 UTC, blackwaterbread commented
Great, let me know if there's anything else need to work on

2024-07-17 14:54 UTC, merged