HQ UI rework
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #248
Opened 2024-07-13 19:44 UTC by wersal454

## What type of PR is this?
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:

Attempt at adding more filtering into HQ vehicle store

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

********************************************************
Notes:
not worki at the moment (13.07.2024)

2024-09-02 11:04 UTC, wersal454 commented
Might need to make a port to community version to maybe receive help with this one

2024-10-18 22:02 UTC, wersal454 commented
done

2024-10-27 15:07 UTC, SilenceIsFatto requested changes

2024-10-27 15:07 UTC, SilenceIsFatto commented on A3A/addons/scrt/Encounter/fn_encounter_HeliSlingloadCargo.sqf
was this meant for another PR?

2024-10-27 15:09 UTC, wersal454 commented on A3A/addons/scrt/Encounter/fn_encounter_HeliSlingloadCargo.sqf
no, it's just my hq is set near CSAT base, so I noticed that it wasn't working as intended, decided to fix it before I forget

2024-11-23 13:50 UTC, SilenceIsFatto approved these changes

2024-11-26 14:15 UTC, SilenceIsFatto requested changes
The UI is nice to use, very good

I think that the stringtables should be updated to capitalize the vehicle type, e.g: `Civilian Cars` rather than `Civilian cars`. It's minor but this way it will maintain visual consistency with the arms dealer

Also there's a minor issue with the CfgFunctions, it's a simple fix. See the review

2024-11-26 14:15 UTC, SilenceIsFatto commented on A3A/addons/gui/CfgFunctions.hpp
> +            class buyVehicleDialogStatics {};
None of these functions exist anymore

```suggestion
```

2024-12-01 13:06 UTC, Silence-112 approved these changes
Looks fine now

2024-12-05 15:10 UTC, merged