Fix for spectrum device hacking working only for JIP
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #278
Opened 2024-08-11 19:55 UTC by wersal454

## What type of PR is this?
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

********************************************************
Notes:

2024-08-16 13:38 UTC, SilenceIsFatto requested changes

2024-08-16 13:38 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Supports/fn_SUP_cruiseMissileAvailable.sqf
> +if(tierWar < 6) exitWith {-1}; don't forget to uncommnet it
```suggestion
if(tierWar < 6) exitWith {-1};
```

2024-08-17 11:54 UTC, SilenceIsFatto approved these changes

2024-08-28 11:44 UTC, wersal454 commented
Might need to change "TARGET" to "AREA" in init supports for cruise missile

2024-08-30 15:53 UTC, merged