Maxx
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #289
Opened 2024-08-20 16:53 UTC by UAC-MaxxLite

## What type of PR is this?
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:
-Changed the behavior of builderboxes (now can be placed on roads)
-Changed the way to decide which items are in the builder box depending on map
-Added more items to the builder box for better usability

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:
Test with the community for balancing prices
********************************************************
Notes:
Prices may not be balanced.
Maps may have the wrong presets of items loaded in due to lack of map knowledge by Maxx.

2024-08-20 17:08 UTC, SilenceIsFatto requested changes

2024-08-20 17:08 UTC, SilenceIsFatto commented on A3A/addons/maps/Antistasi_Altis.Altis/mapInfo.hpp
> +		BUILDABLES_UNIVERSAL
When using macros you should always leave the last ; or , out of the definition. This way when we're defining them, we can use those as usual and it flows better.

```suggestion
		BUILDABLES_HISTORIC,
		BUILDABLES_MODERN_SAND,
		BUILDABLES_ARID,
		BUILDABLES_UNIVERSAL,
```

2024-08-20 17:08 UTC, SilenceIsFatto commented on A3A/addons/maps/BuildObjectsList.hpp
> +#define BUILDABLES_UNIVERSAL {"Land_GuardTower_02_F", 150}, {"Land_PortableLight_double_F", 50}, {"Land_LampShabby_F", 75}, {"Land_LampHarbour_F", 100}, {"Land_BarGate_F", 100}, {"Land_SandbagBarrica
```suggestion
#define BUILDABLES_MODERN_GREEN {"Land_GuardTower_01_F", 300}, {"Land_HBarrier_01_line_3_green_F", 100}, {"Land_HBarrier_01_line_5_green_F", 150}, {"Land_HBarrier_01_line_1_green_F", 50}, {"Land_HBarrier_01_big_4_green_F", 300}, {"Land_HBarrier_01_wall_corridor_green_F", 250}, {"Land_HBarrier_01_wall_corner_green_F", 250}, {"Land_HBarrier_01_wall_6_green_F", 450}, {"Land_HBarrier_01_wall_4_green_F", 400}, {"Land_HBarrier_01_big_tower_green_F", 500}

#define BUILDABLES_MODERN_SAND {"Land_GuardTower_01_F", 300}, {"Land_HBarrier_3_F", 100}, {"Land_HBarrier_5_F", 150}, {"Land_HBarrier_1_F", 50}, {"Land_HBarrier_Big_F", 300}, {"Land_HBarrierWall_corridor_F", 250}, {"Land_HBarrierWall_corner_F", 250}, {"Land_HBarrierWall6_F", 450}, {"Land_HBarrierWall4_F", 400}, {"Land_HBarrierTower_F", 500}

#define BUILDABLES_HISTORIC {"Land_Tyres_F", 20}, {"Land_Barricade_01_10m_F", 50}, {"Land_Barricade_01_4m_F", 30}, {"Land_DeerStand_01_F", 100}

#define BUILDABLES_SCIFI {"A3AU_Cargo_Post", 450}, {"A3AU_Cargo_Tower", 1000}, {"A3AU_Cargo_HQ", 500}, {"A3AU_Cargo_House", 350}

//Map Climate Modifiers (What type of terrain is the biggest area of the map)
#define BUILDABLES_ARID {"Land_BagFence_Corner_F", 10}, {"Land_BagFence_End_F", 10}, {"Land_BagFence_Long_F", 30}, {"Land_BagFence_Round_F", 30}, {"Land_BagFence_Short_F", 20}

#define BUILDABLES_TEMPERATE {"Land_BagFence_01_corner_green_F", 10}, {"Land_BagFence_01_end_green_F", 10}, {"Land_BagFence_01_long_green_F", 30}, {"Land_BagFence_01_round_green_F", 30}, {"Land_BagFence_01_short_green_F", 20}

#define BUILDABLES_ARCTIC {"Land_BagFence_Corner_F", 10}, {"Land_BagFence_End_F", 10}, {"Land_BagFence_Long_F", 30}, {"Land_BagFence_Round_F", 30}, {"Land_BagFence_Short_F", 20}

#define BUILDABLES_TROPIC {"Land_BagFence_01_corner_green_F", 10}, {"Land_BagFence_01_end_green_F", 10}, {"Land_BagFence_01_long_green_F", 30}, {"Land_BagFence_01_round_green_F", 30}, {"Land_BagFence_01_short_green_F", 20}

//Modlist Modifiers (Only for maps that have dependency mods with usable items in them)
#define BUILDABLES_CUP {"TK_GUE_WarfareBBarrier5x_EP1", 600}, {"TK_GUE_WarfareBBarrier10xTall_EP1", 700}, {"TK_WarfareBBarrier10x_EP1", 650}, {"Land_Misc_deerstand", 60}, {"Land_Hlaska", 120}

#define BUILDABLES_JBAD {"jbad_Wall_L_2m5", 100}, {"jbad_Wall_L_2m5_corner", 75}, {"jbad_Wall_L_2m5_gate", 75}, {"jbad_wall_l_5m", 150}, {"jbad_wall_L_5m_hole_big", 125}

//cDLC Modifiers (For cDLC dependent maps)
#define BUILDABLES_SPE
#define BUILDABLES_SOGPF
#define BUILDABLES_GM
#define BUILDABLES_WS

//Ending Build List. (Universal Items)
#define BUILDABLES_UNIVERSAL {"Land_GuardTower_02_F", 150}, {"Land_PortableLight_double_F", 50}, {"Land_LampShabby_F", 75}, {"Land_LampHarbour_F", 100}, {"Land_BarGate_F", 100}, {"Land_SandbagBarricade_01_half_F", 40}, {"Land_SandbagBarricade_01_hole_F", 40}, {"Land_SandbagBarricade_01_F", 40}, {"A3AU_RebHelipad_Square_F", 100}, {"A3AU_RebHelipad_Circle_F", 100}, {"Land_BagBunker_Large_F", 250}, {"Land_BagBunker_Small_F", 150}, {"Land_Bunker_02_light_double_F", 500}, {"Land_GuardBox_01_brown_F", 100}, {"Land_CzechHedgehog_01_new_F", 15}, {"Land_Razorwire_F", 15}
```

2024-08-20 17:08 UTC, SilenceIsFatto commented on A3A/addons/maps/BuildObjectsList.hpp
Make sure to update every mapInfo.hpp with these changes

2024-08-20 17:25 UTC, SilenceIsFatto commented
Also rename the PR to match what it actually does

2024-08-20 22:56 UTC, SilenceIsFatto requested changes

2024-08-20 22:56 UTC, SilenceIsFatto commented on A3A/addons/maps/Antistasi_Stratis.Stratis/mapInfo.hpp
> +		BUILDABLES_GM,,
Double comma
```suggestion
		BUILDABLES_GM,
```

2024-08-20 22:56 UTC, SilenceIsFatto commented on A3A/addons/maps/Antistasi_Stratis.Stratis/mapInfo.hpp
> +		#define BUILDABLES_WS,
Random define here
```suggestion
		BUILDABLES_WS,
```

2024-08-20 22:56 UTC, SilenceIsFatto commented on A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/mapInfo.hpp
> +		BUILDABLES_GM,,
Double comma
```suggestion
		BUILDABLES_GM,
```

2024-08-20 22:56 UTC, SilenceIsFatto commented on A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/mapInfo.hpp
> +		BUILDABLES_GM,,
Double comma
```suggestion
		BUILDABLES_GM,
```

2024-08-20 22:56 UTC, SilenceIsFatto commented on A3A/addons/scrt/UI/fn_ui_setAvailableBuildingTypes.sqf
Does this actually get used anywhere?

2024-08-20 22:56 UTC, SilenceIsFatto commented on A3A/addons/maps/Antistasi_Stratis.Stratis/mapInfo.hpp
Make sure the DLC specific changes aren't in the final version that gets merged. Other people use Stratis for debug too, making all of these mods and DLCs a requirement is not a good idea

2024-08-21 04:14 UTC, UAC-MaxxLite commented on A3A/addons/scrt/UI/fn_ui_setAvailableBuildingTypes.sqf
dont think so

2024-08-21 04:16 UTC, UAC-MaxxLite commented on A3A/addons/maps/Antistasi_Stratis.Stratis/mapInfo.hpp
if you dont have the mod/requirements it will load as missing and wont create errors while building

2024-08-21 16:37 UTC, SilenceIsFatto approved these changes
should be good

2024-08-21 18:31 UTC, merged