debatable community ports
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #311
Opened 2024-09-01 20:10 UTC by wersal454

## What type of PR is this?
1. [ ] Bug
2. [x] Change
3. [x] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:

ports:
#3266
#3375
#3372
#3369
#3364
#3349
#3273
#3231

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

********************************************************
Notes:
Some of the ports need heavy testing and probably some additional work

2024-09-09 22:22 UTC, SilenceIsFatto requested changes
Is there actually a difference between east and opfor?

The [Side](https://community.bistudio.com/wiki/Side) page shows that OPFOR is referenced by both east and opfor

![image](https://github.com/user-attachments/assets/63e29356-8e58-4676-b981-42236e7dd3c3)

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/Includes/common.inc
> +#define Faction(SIDE) (switch SIDE do {case west:{A3A_faction_occ}; case east:{A3A_faction_inv}; case resistance:{A3A_faction_reb}; case civilian:{A3A_faction_civ}; default {Error_1("Bad side passed
Rivals aren't in this macro because invaders are also east, no?

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Base/fn_moveOutCrew.sqf
> +if ((side _vehicle ==  west) || (side _vehicle == east)/*  && alive driver _vehicle */) exitWith {  /// might need to add opfor here for rivals
same here, rivals are east too

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/functions/CREATE/fn_attackHQ.sqf
> +//bigAttackInProgress = true; publicVariable "bigAttackInProgress";
Surely a HQ attack is a big attack?

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/functions/CREATE/fn_crewTypeForVehicle.sqf
> +private _sideIndex = [west, east, independent, civilian, opfor] find _side;
east is opfor, so isn't this pointless?

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf
> +//bigAttackInProgress = true; publicVariable "bigAttackInProgress";
Surely a punishment is a big attack?

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/functions/CREATE/fn_wavedAttack.sqf
> +//bigAttackInProgress = true; publicVariable "bigAttackInProgress";
Surely this is a big attack?

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/functions/OrgPlayers/fn_unitTraits.sqf
I think the question here is not `why not?`, but rather `why?`

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/functions/REINF/fn_postmortem.sqf
> +    if (_victim isKindOf "CAManBase" and !isNull objectParent _victim) then {
```suggestion
    if (_victim isKindOf "CAManBase" and !(isNull (objectParent _victim))) then {
```

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Templates/Itemsets/fn_itemset_medicalSupplies.sqf
> +	[A3A_faction_occ, A3A_faction_inv, A3A_faction_reb, A3A_faction_civ] #([west, east, independent, civilian, opfor] find _side);
As said above, aren't east and opfor the exact same?

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Templates/fn_compatibilityLoadFaction.sqf
east = opfor?

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Templates/fn_loadRivals.sqf
> +    [_faction, opfor, _file] call A3A_fnc_TV_verifyAssets;
east is opfor, this doesn't do anything

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/functions/init/fn_initVarCommon.sqf
> +Rivals = opfor;
east/opfor issue

2024-09-09 22:22 UTC, SilenceIsFatto commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +    private _side = [west, east, resistance, civilian, opfor] # _forEachIndex;
east/opfor issue

2024-09-10 14:46 UTC, wersal454 commented
Problem with east and opfor, is that for some reason antistasi can't decide what driver to put inside the vehicles that double in main factions and rivals, so when it tries to spawn such vehicles, those spawn with error and with no drivers

2024-09-15 16:40 UTC, SilenceIsFatto commented
Do these changes actually fix that or are they just hopeful changes?

2024-09-16 10:09 UTC, wersal454 commented
> Do these changes actually fix that or are they just hopeful changes?

Haven't tested it, hopefully I going to test by the end of the week

2024-10-06 21:44 UTC, SilenceIsFatto commented
I'll disregard the opfor/east issues, there's only 2 questions left:

[1](https://github.com/SilenceIsFatto/A3-Antistasi-Ultimate/pull/311/files/c13cbfd5435b53a4405530a1ea575eff37545881#diff-2c3c685c43d9768f1e3f68c81c7033730109eaec1280d0bcc53267f8583f1273)

[2](https://github.com/SilenceIsFatto/A3-Antistasi-Ultimate/pull/311/files/c13cbfd5435b53a4405530a1ea575eff37545881#diff-df13112a073848af2e4256234949a1b78b2e3a35b05c6853d927c425b0df53ba)

2024-10-06 22:02 UTC, wersal454 commented
Giving rivals their own side won't work(probably), so I think it would be possible to simply give rivals their own createunit and createvehiclecrew functions, so game won't be confused when deciding what unit to create. This whole opfor/east stuff I did should be removed from this PR. I hope it's somewhat simple. In regards to Bigattack stuff, I don't remember, one of the pr from community moved bigattack modifer somewhere, so I commented it out(just in case). So bigattack will still happen, but code for it, is in different place(in to check where))

2024-10-08 20:23 UTC, wersal454 commented on A3A/addons/core/functions/OrgPlayers/fn_unitTraits.sqf
None of the roles, except commander do have explosive specialist trait, so engineer would seem to be fitting

2024-10-08 20:26 UTC, wersal454 commented
> Giving rivals their own side won't work(probably), so I think it would be possible to simply give rivals their own createunit and createvehiclecrew functions, so game won't be confused when deciding what unit to create. This whole opfor/east stuff I did should be removed from this PR. I hope it's somewhat simple. In regards to Bigattack stuff, I don't remember, one of the pr from community moved bigattack modifer somewhere, so I commented it out(just in case). So bigattack will still happen, but code for it, is in different place(to check where))

![image](https://github.com/user-attachments/assets/2691d938-0871-4c5c-9367-dff0ac07082c)

2024-10-09 05:36 UTC, SilenceIsFatto reviewed
I believe it's fine to test

2024-11-05 18:13 UTC, SilenceIsFatto commented on A3A/addons/core/functions/CREATE/fn_attackHQ.sqf
> +//bigAttackInProgress = true; publicVariable "bigAttackInProgress";
This comment should be removed given it dictates if extra missions are created during already laggy events

2024-11-05 18:13 UTC, SilenceIsFatto commented on A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf
> +//bigAttackInProgress = true; publicVariable "bigAttackInProgress";
This comment should be removed given it dictates if extra missions are created during already laggy events

2024-11-05 19:45 UTC, SilenceIsFatto commented
Actually merged in #370 due to branch funnies, going to merge this one to preserve the description/conversation

2024-11-05 19:45 UTC, merged