Air Patrol Vehicle category port
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #312
Opened 2024-09-01 20:41 UTC by wersal454

## What type of PR is this?
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

ported #3208

modified it to make more sense in my opinion

### Please verify the following.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

********************************************************
Notes:

2024-09-09 22:01 UTC, SilenceIsFatto approved these changes
Looks fine, change the base branch to unstable

2024-09-11 14:02 UTC, wersal454 commented
![image](https://github.com/user-attachments/assets/863fb9bb-d402-4415-a4e4-fbadbe6dc3c2)
pls, check those 2, they poped up during merge conflict

2024-09-11 15:47 UTC, wersal454 commented
> ![image](https://private-user-images.githubusercontent.com/29953387/366489207-863fb9bb-d402-4415-a4e4-fbadbe6dc3c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjk4NjQsIm5iZiI6MTcyNjA2OTU2NCwicGF0aCI6Ii8yOTk1MzM4Ny8zNjY0ODkyMDctODYzZmI5YmItZDQwMi00NDE1LWE0ZTQtZmJhZGJlNmRjM2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE1NDYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNjk0OTAwNzZiODZmZWFkZmMyZDdiMGNiMTMwZTA5YjJiZmUzYzQ0M2FmMWRjZjlmNWI1M2ZlYmZlNzhiODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MquGHsslimjc5it2rdGhx3rG0ZuYrEecs_KNymVtIzE) pls, check those 2, they poped up during merge conflict

I think, those are doubles, need to delete them

2024-09-25 13:09 UTC, stutpip123 commented
if this works, said category needs adding to all templates with relevant helicopters

2024-12-30 15:23 UTC, SilenceIsFatto requested changes
Looks fine, just needs to have `vehiclesAirPatrol` added to some more templates

For now it should be fine with just vanilla CUP and RHS

2025-01-08 16:20 UTC, SilenceIsFatto reviewed
Some small issues but seems to be fine otherwise, I tested most factions with different DLC combinations

2025-01-08 16:20 UTC, Silence-112 commented on A3A/addons/core/Templates/Templates/#Examples/FactionExample.sqf
> +["vehiclesAirPatrol", _airPatrol] call _fnc_saveToTemplate;             // preferably light helicopters(armed or unarmed), used in base patrol near bases
```suggestion
["vehiclesAirPatrol", []] call _fnc_saveToTemplate;             // preferably light helicopters(armed or unarmed), used in base patrol near bases
```

2025-01-08 16:20 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/FactionDefaults/EnemyDefaults.sqf
> +["vehiclesAirPatrol", _airPatrol] call _fnc_saveToTemplate;
```suggestion
["vehiclesAirPatrol", []] call _fnc_saveToTemplate;
```

2025-01-10 15:28 UTC, Silence-112 approved these changes

2025-01-14 15:56 UTC, merged