Trader fast travel check
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #333
Opened 2024-09-24 15:20 UTC by AtteKarppinen

## What type of PR is this?
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:
Fixing an issue where player could fast travel to trader before finishing the trader quest.

- Updated publicVariable isTraderQuestAssigned on trader quest completion
- Added string ID with localisations fo when FT is prevented (translated using Google Translator)

### Please specify which Issue this PR Resolves (If Applicable).
--

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [x] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:
Should be quite straightforward but further testing won't hurt;
Start a new save and spawn trader quest with `[] remoteExec ["SCRT_fnc_trader_prepareTraderQuest", 2];`

FT to trader should be prevented until finishing the quest. After finishing the quest, check that FT works as expected. Redo find trader task and verify again that FT is not possible while trader quest is active.

********************************************************
Notes: Might cause conflicts with https://github.com/SilenceIsFatto/A3-Antistasi-Ultimate/pull/332 but let's handle those if the time comes.

2024-09-25 12:54 UTC, SilenceIsFatto approved these changes
Looks fine, we'll test it with #332

2024-10-04 15:25 UTC, stutpip123 commented
after server restart, the need to physically reach the dealer is reset, even when discovered

2024-10-25 12:18 UTC, SilenceIsFatto requested changes
The new variables probably need to be saved so as to not break things upon an environment restart

> ![image](https://github.com/user-attachments/assets/8447917d-f2ca-4f88-9f6d-ff6d3fb0a7f5)

2024-10-25 13:16 UTC, AtteKarppinen commented
Unfortunately, I'll be AFK for the following four weeks. Checking for `isTraderQuestCompleted `is not necessary, just a cautious approach. But there's some logic flaw (I think) with the `isTraderQuestAssigned`. When server restarts, it is always set to true. Culprit is likely fn_loadStat.sql but without investigating with time, I dare not touch it.

2025-02-02 15:17 UTC, stutpip123 commented
this PR continued in #450

2025-02-02 15:17 UTC, closed without merging