JCA Arms Dealer
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #337
Opened 2024-09-25 21:52 UTC by Azodion

## What type of PR is this?
1. [ ] Bug
2. [x] Change
3. [x] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:
Added JCA Infantry Arsenal to Arms Dealer - [Main Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=3333302397)
### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

********************************************************
Notes:
Works

2024-09-26 13:02 UTC, SilenceIsFatto requested changes
Just needs naming consistency, is otherwise fine

2024-09-26 13:02 UTC, SilenceIsFatto commented on A3A/addons/ultimate/config/trader/cfgTraderWeapons.hpp
> +        class JCAArsenal_Compat : weapons_base
```suggestion
        class weapons_jca : weapons_base
```

2024-09-26 13:02 UTC, SilenceIsFatto commented on A3A/addons/ultimate/config/trader/cfgTraderAddons.hpp
> +        weapons = "JCAArsenal_Compat";
```suggestion
        weapons = "weapons_jca";
```

2024-09-26 13:02 UTC, SilenceIsFatto commented on A3A/addons/ultimate/config/trader/cfgTraderAddons.hpp
> +    class addons_JCAArsenal : addons_base
```suggestion
    class addons_jca : addons_base
```

2024-09-26 13:02 UTC, SilenceIsFatto commented on A3A/addons/hals/Addons/store/config.hpp
> +		class JCA_Arsenal_Stock
```suggestion
		class jca_stock
```

2024-09-26 13:02 UTC, SilenceIsFatto commented on A3A/addons/ultimate/config/trader/cfgTraderWeapons.hpp
> +            prefix = "JCA_Arsenal_Stock"
```suggestion
            prefix = "jca_stock"
```

2024-09-27 12:16 UTC, wersal454 commented
I believe most(if not all) of this stuff is in aegis, but I think it won't hurt if it will double

2024-09-27 17:11 UTC, SilenceIsFatto approved these changes
lgtm

2024-10-21 08:37 UTC, merged