Vehicle to emplacement
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #376
Opened 2024-10-27 20:49 UTC by wersal454

## What type of PR is this?
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:

Attempt to allow AI to man gunner seats(would be nice to add commander as well) in vehicles that were "converted" to emplacements(I.E. "Boss" pressed the button in Y menu and vehicle is now open for the AI like statics)

I don't allow ai to drive vehicles(yet(or ever)) because I didn't figure out how to store their original position

Also no air vehicles, because... well no driver = no point and idk, don't think it good thing to do, maybe someday and in different form

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #254!"

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (I need help with this one)

### How can the changes be tested?
Steps:
Spawn vehicle and go into Y menu and in ai management press "moveout crew"/buttom right button(I didn't bother to change the name)
********************************************************
Notes:
I do need help with this one, cause for some reason game deletes vehicles that were meant to be saved after save load or on server restart

2024-10-28 21:18 UTC, wersal454 commented
I think changes made to _updatestatics fixies #280

2024-12-14 00:28 UTC, wersal454 commented
I think it works now

Decided to go with an simpler solution

2024-12-17 13:52 UTC, wersal454 commented
forgot to mention, I managed to allow AI to man a commander seats(if vehicle/static has it)

2025-01-08 16:39 UTC, SilenceIsFatto commented on A3A/addons/core/functions/AI/fn_landThreatEval.sqf
> +		_threat = _threat + ({typeOf _x in FactionGet(reb,"staticMortars")} count _staticsX) + (2*({typeOf _x in FactionGet(reb,"staticAT")} count _staticsX)) ///emmm, we should also check for other factio
I suppose, have you thought of a method of doing so?

2025-01-08 16:39 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Save/fn_saveLoop.sqf
> -["staticsX", _arrayEst] call A3A_fnc_setStatVariable;
Why is this being removed?

2025-01-08 18:10 UTC, wersal454 commented on A3A/addons/core/functions/AI/fn_landThreatEval.sqf
> +		_threat = _threat + ({typeOf _x in FactionGet(reb,"staticMortars")} count _staticsX) + (2*({typeOf _x in FactionGet(reb,"staticAT")} count _staticsX)) ///emmm, we should also check for other factio
faction(all ......

kinda like that, not sure

2025-01-08 18:13 UTC, wersal454 commented on A3A/addons/core/functions/Save/fn_saveLoop.sqf
> -["staticsX", _arrayEst] call A3A_fnc_setStatVariable;
oh, because there were two of those
![image](https://github.com/user-attachments/assets/e5cedcc4-e1a7-4d27-bad5-b903bc7668fe)

2025-01-15 09:29 UTC, wersal454 commented on A3A/addons/core/functions/AI/fn_landThreatEval.sqf
> +		_threat = _threat + ({typeOf _x in FactionGet(reb,"staticMortars")} count _staticsX) + (2*({typeOf _x in FactionGet(reb,"staticAT")} count _staticsX)) ///emmm, we should also check for other factio
What do you think?

When I was writing that comment I was thinking that threat evaluation should take into consideration if rebels are occupying statics that are defined in enemy templates and not defined in rebel. Otherwise it will ignore them I think

2025-02-07 13:02 UTC, SilenceIsFatto commented on A3A/addons/core/functions/AI/fn_landThreatEval.sqf
> +		_threat = _threat + ({typeOf _x in FactionGet(reb,"staticMortars")} count _staticsX) + (2*({typeOf _x in FactionGet(reb,"staticAT")} count _staticsX)) ///emmm, we should also check for other factio
I imagine the lack of Occ/Inv check might have something to do with the fact that it loops through every single zone

Realistically I don't think it'd make much of a visible difference

2025-02-07 13:23 UTC, wersal454 commented on A3A/addons/core/functions/AI/fn_landThreatEval.sqf
> +		_threat = _threat + ({typeOf _x in FactionGet(reb,"staticMortars")} count _staticsX) + (2*({typeOf _x in FactionGet(reb,"staticAT")} count _staticsX)) ///emmm, we should also check for other factio
so you think enemy doesn't need to account for friendly statics that were taken over by rebels, correct ?

2025-02-07 13:25 UTC, SilenceIsFatto commented on A3A/addons/core/functions/AI/fn_landThreatEval.sqf
> +		_threat = _threat + ({typeOf _x in FactionGet(reb,"staticMortars")} count _staticsX) + (2*({typeOf _x in FactionGet(reb,"staticAT")} count _staticsX)) ///emmm, we should also check for other factio
Not when it'll need a bunch of extra checks that are already running in a chunky forEach loop

2025-02-07 13:36 UTC, wersal454 commented on A3A/addons/core/functions/AI/fn_landThreatEval.sqf
> +		_threat = _threat + ({typeOf _x in FactionGet(reb,"staticMortars")} count _staticsX) + (2*({typeOf _x in FactionGet(reb,"staticAT")} count _staticsX)) ///emmm, we should also check for other factio
well, okay then

2025-02-08 16:19 UTC, SilenceIsFatto reviewed
Why is StaticWeapon being completely ditched?

Also when testing it, the only thing that I could get to save was a truck that spawned at the same outpost I was testing it on (or am I confusing this PR with #390?)

2025-02-08 16:19 UTC, SilenceIsFatto commented on A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
> +		if (_side == teamPlayer && !isNil {serverInitDone}) then { [_veh] remoteExec ["A3A_fnc_updateRebelStatics", 2] };
```suggestion
		if (_side == teamPlayer && {!isNil "serverInitDone"}) then { [_veh] remoteExec ["A3A_fnc_updateRebelStatics", 2] };
```

2025-02-08 16:46 UTC, wersal454 commented
> Why is StaticWeapon being completely ditched?
> 
> Also when testing it, the only thing that I could get to save was a truck that spawned at the same outpost I was testing it on (or am I confusing this PR with #390?)

#390 has different functionality completely

as for your test, you managed to save a truck but no statics?

2025-02-10 18:53 UTC, wersal454 commented
https://drive.google.com/file/d/1p76qweMG8Zb3IPCv_uGEzTTWeItYEiIT/view?usp=drive_link what this PR does

2025-10-29 00:16 UTC, jwoodruff40 requested changes
A bunch of minor changes needed.

Also, in `fn_loadStat` LN 398-402:

```
                if (isNil {_veh getVariable "A3A_canGarage"}) then {        // Buyable items should set this
                    switch true do {
                        case (_veh isKindOf "StaticWeapon");
                        case (_veh isKindOf "LandVehicle");
                        case (_veh isKindOf "Ship"): {
                            staticsToSave pushBack _veh;
                        };
```

courtesy of UnseenKill

2025-10-29 00:16 UTC, jwoodruff40 commented on A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
> +_veh setVehicleRadar 1; ///might break something ////// fix (kinda) for inactive rebel SAMs and radars
```suggestion
_veh setVehicleRadar (getNumber (configOf _veh >> "radarType") in [2,4]);
```

courtesy of UnseenKill

2025-10-29 00:16 UTC, jwoodruff40 commented on A3A/addons/core/functions/UtilityItems/fn_initObject.sqf
> +_object setVehicleRadar 1; /// fix (kinda) for inactive rebel SAMs and radars
```suggestion
_object setVehicleRadar (getNumber(configOf _veh >> "radarType") in [2, 4]);
```

courtesy of UnseenKill

2025-10-29 00:16 UTC, jwoodruff40 commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +    };
```suggestion
```

Does the same thing as "vehicleStatic" case

2025-10-29 00:16 UTC, jwoodruff40 commented on A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
>  	};
```suggestion
	if !(_typeX isKindOf "StaticMortar") then {
	    [_veh, "vehiclestatic"] remoteExec ["A3A_fnc_flagAction", [teamPlayer,civilian], _veh];
		if (_veh in UngaragedVehicles) then {
			_veh setVariable ["lockedForAI", true, true]; 
		} else {
			if (_side == teamPlayer && {!isNil "serverInitDone"}) then { [_veh] remoteExec ["A3A_fnc_updateRebelStatics", 2] };
		};
    };
```

2025-10-29 00:16 UTC, jwoodruff40 commented on A3A/addons/core/functions/CREATE/fn_createSDKgarrisons.sqf
> +        private _turretPath = _x#1;
```suggestion
        _x params ["_role", "_turretPath"];
```

2025-10-29 00:16 UTC, jwoodruff40 commented on A3A/addons/core/functions/CREATE/fn_createSDKgarrisons.sqf
> +        private _unit = [_unitGroup, _garrison#_index, _positionX, [], 0, "NONE"] call A3A_fnc_createUnit;
```suggestion
        private _unit = [_unitGroup, _garrison select _index, _positionX, [], 0, "NONE"] call A3A_fnc_createUnit;
```

2025-10-29 00:16 UTC, jwoodruff40 commented on A3A/addons/core/functions/CREATE/fn_createSDKgarrisons.sqf
> +	_groupX setCombatMode "YELLOW";
```suggestion
	_groupX setCombatMode "GREEN";
```

YELLOW is a bad idea. AI garrisons should not be engaging anything they see and increasing enemy aggro, with no inputs from actual players. Defend themselves, sure, but no go out of their way to attack.

https://community.bistudio.com/wiki/Combat_Modes

2025-10-29 00:16 UTC, jwoodruff40 commented on A3A/addons/core/functions/Save/fn_savePlayer.sqf
> +			if (_x == driver _veh || {_x == gunner _veh && _veh isKindOf "LandVehicle"} || {_x == gunner _veh && _veh isKindOf "Ship"}) then {
```suggestion
			if (_x == driver _veh || {_x == gunner _veh && (_veh isKindOf "LandVehicle" || {_veh isKindOf "Ship"})}) then {
```

2025-10-29 00:16 UTC, jwoodruff40 commented on A3A/addons/scrt/UILayouts/menu.hpp
> +		}; */
```suggestion
```

2025-10-29 00:16 UTC, jwoodruff40 commented on A3A/addons/core/CfgFunctions.hpp
> +            class vehicleBoxRestore {};
```suggestion
```

duplicate

2025-10-29 00:16 UTC, jwoodruff40 commented on A3A/addons/core/functions/Base/fn_updateRebelStatics.sqf
> +    _veh setVehicleRadar 1;
```suggestion
    _veh setVehicleRadar (getNumber (configOf _veh >> "radarType") in [2,4]);
```

2025-10-29 00:16 UTC, jwoodruff40 commented on A3A/addons/core/functions/Base/fn_updateRebelStatics.sqf
> +_staticGroup setCombatMode "YELLOW";
```suggestion
_staticGroup setCombatMode "WHITE";
```

See other comment

2025-10-30 09:15 UTC, wersal454 commented
@UnseenKill any source on (getNumber(configOf _veh >> "radarType") in [2, 4]) ?

2025-10-30 09:20 UTC, UnseenKill commented
> @UnseenKill any source on (getNumber(configOf _veh >> "radarType") in [2, 4]) ?

https://community.bistudio.com/wiki/Arma_3:_Targeting_Config_Reference#radarType

2025-10-30 09:26 UTC, wersal454 commented
> > @UnseenKill any source on (getNumber(configOf _veh >> "radarType") in [2, 4]) ?
> 
> https://community.bistudio.com/wiki/Arma_3:_Targeting_Config_Reference#radarType

I guess this makes sense, though, I don't think `setVehicleRadar 1` gives any error if vehicle has an actual radar or not

2025-10-30 09:31 UTC, UnseenKill commented
> > > @UnseenKill any source on (getNumber(configOf _veh >> "radarType") in [2, 4]) ?
> > 
> > 
> > https://community.bistudio.com/wiki/Arma_3:_Targeting_Config_Reference#radarType
> 
> I guess this makes sense, though, I don't think `setVehicleRadar 1` gives any error if vehicle has an actual radar or not

Well, _somebody_ left a comment, that setting the radar to ON _might_ break stuff. No further detail. But it's there for a reason and some time, so better to go it the safe way, no?

2025-10-30 09:37 UTC, UnseenKill requested changes

2025-10-30 09:37 UTC, UnseenKill commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +    };
Switch case fallback, since it's duplicate code.

```suggestion
    case "vehiclestatic";
```

2025-10-30 09:37 UTC, UnseenKill commented on A3A/addons/garage/Public/config.inc
> +		publicVariable "UngaragedVehicles";
I don't like forcing new stuff unto players. This retains the old behavior, so player will have to explicitly choose which vehicle should be crewed and which - in case e.g. of stand-by vehicles for players - aren't crewed.

```suggestion
        ungaragedVehicles pushBack _this; 
		publicVariable "ungaragedVehicles";
		
		// Auto-crew static weapons, but have the player explicitly choose vehicles
		if !(_this isKindOf "StaticWeapon") then {
		    _this setVariable["lockedForAI", true, true];
		}
```

2025-10-30 09:37 UTC, UnseenKill commented on A3A/addons/core/functions/Base/fn_updateRebelStatics.sqf
> +};
All other global variables are expressed in dromedary case. We should stick to one style.

```suggestion
if (_target in ungaragedVehicles) then {
    private _deleteVeh = ungaragedVehicles find _target;
    ungaragedVehicles deleteAt _deleteVeh;
    publicVariable "ungaragedVehicles";
};
```

2025-10-30 09:37 UTC, UnseenKill commented on A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
> +		if (_veh in UngaragedVehicles) then {
```suggestion
		if (_veh in ungaragedVehicles) then {
```

2025-10-30 09:37 UTC, UnseenKill commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +DECLARE_SERVER_VAR(UngaragedVehicles, []);
```suggestion
DECLARE_SERVER_VAR(ungaragedVehicles, []);
```

2025-10-30 09:41 UTC, wersal454 commented
> > > > @UnseenKill any source on (getNumber(configOf _veh >> "radarType") in [2, 4]) ?
> > > 
> > > 
> > > https://community.bistudio.com/wiki/Arma_3:_Targeting_Config_Reference#radarType
> > 
> > 
> > I guess this makes sense, though, I don't think `setVehicleRadar 1` gives any error if vehicle has an actual radar or not
> 
> Well, _somebody_ left a comment, that setting the radar to ON _might_ break stuff. No further detail. But it's there for a reason and some time, so better to go it the safe way, no?

I meant that it will turn on radar on some vehicle that for whatever reason better not have it turned on 🤷‍♂️. But, yeah sure

2025-10-30 09:42 UTC, wersal454 commented
Also, what's that class vehicleBoxRestore {}; ?

2025-10-30 09:46 UTC, UnseenKill commented on A3A/addons/core/functions/Base/fn_updateRebelStatics.sqf
> +            } forEach _units;
```suggestion
            // Sanity check; vehicle _can_ be gone, blown up, whatever
            if isNull(_veh) exitWith {};
            _units select { !isNull _x && { isNull objectParent _x } && { assignedVehicleRole _x isNotEqualTo [] } } apply {
                switch (assignedVehicleRole _x select 0) do {
                    case "commander": { _x moveInCommander _veh };
                    case "gunner": { _x moveInGunner _veh };
                    case "turret": {
                            private _path = _x call BIS_fnc_turretPath;
                            if !(_path isEqualTo []) then {
                                _x moveInTurret [_veh, _path];
                            };
                    };
                };
            };
```

2025-10-30 09:51 UTC, UnseenKill commented
> > > > > @UnseenKill any source on (getNumber(configOf _veh >> "radarType") in [2, 4]) ?
> > > > 
> > > > 
> > > > https://community.bistudio.com/wiki/Arma_3:_Targeting_Config_Reference#radarType
> > > 
> > > 
> > > I guess this makes sense, though, I don't think `setVehicleRadar 1` gives any error if vehicle has an actual radar or not
> > 
> > 
> > Well, _somebody_ left a comment, that setting the radar to ON _might_ break stuff. No further detail. But it's there for a reason and some time, so better to go it the safe way, no?
> 
> I meant that it will turn on radar on some vehicle that for whatever reason better not have it turned on 🤷‍♂️. But, yeah sure

I don't understand. You were saying that `setVehicleRadar` doesn't care if the vic has a radar, but if that's what you meant, your change of turning it on for every vehicle kinda contradicts that.

2025-10-30 09:52 UTC, UnseenKill commented
> Also, what's that class vehicleBoxRestore {}; ?

'twas a duplicate.

<img width="633" height="1354" alt="image" src="https://github.com/user-attachments/assets/f0be060e-f011-476d-b36a-ac9a91f7ffe1" />

2025-10-30 10:18 UTC, wersal454 commented on A3A/addons/garage/Public/config.inc
> +		publicVariable "UngaragedVehicles";
<img width="772" height="651" alt="image" src="https://github.com/user-attachments/assets/58f0fa7c-613c-4577-8590-76b8f6b21993" />
Aren't we already doing that? I might remember it wrong.

2025-10-30 10:25 UTC, wersal454 commented on A3A/addons/garage/Public/config.inc
> +		publicVariable "UngaragedVehicles";
I wasn't imagining someone would leave vehicles sitting outside (for possible further use by players). I was thinking it would be usefull for rapid deployment of the defences using vehicles + save said defences during server reset for example (because locked state will stay open, as this happens with static-weapons). And if you lock it from the begging, you will have to run around unlocking everything you set open for the AI to use (including ships)

2025-11-08 15:31 UTC, jwoodruff40 commented on A3A/addons/garage/Public/config.inc
> +		publicVariable "UngaragedVehicles";
Experimental param then?

Something like:

```
class A3A_AIautoCrewVehicles: ExperimentalParams
    {
        title = $STR_params_AIautoCrewVehicles;
        values[] = {0,1};
        texts[] = {$STR_antistasi_dialogs_generic_button_no_text, $STR_antistasi_dialogs_generic_button_yes_text};
        default = 0;
    };
```

and then

```
                // Auto-crew static weapons, but have the player explicitly choose vehicles
		if !(_this isKindOf "StaticWeapon") then {
		    _this setVariable["lockedForAI", A3A_AIautoCrewVehicles, true];
		};
```

2025-11-08 15:51 UTC, jwoodruff40 requested changes

2025-11-08 15:51 UTC, jwoodruff40 commented on A3A/addons/core/functions/UtilityItems/fn_initObject.sqf
> +_object setVehicleRadar (getNumber(configOf _veh >> "radarType") in [2, 4]);
As it turns out, `setVehicleRadar` takes an int (0 for automatic, 1 for forced on, 2 for forced off) not a bool

```suggestion
_object setVehicleRadar ([0, 1] select (getNumber(configOf _veh >> "radarType") in [2, 4]));
```

2025-11-08 15:51 UTC, jwoodruff40 commented on A3A/addons/core/functions/Base/fn_updateRebelStatics.sqf
> +    _veh setVehicleRadar (getNumber (configOf _veh >> "radarType") in [2,4]);
As it turns out, `setVehicleRadar` takes an int (0 for automatic, 1 for forced on, 2 for forced off) not a bool

```suggestion
    _veh setVehicleRadar ([0, 1] select (getNumber(configOf _veh >> "radarType") in [2, 4]));
```

2025-11-08 15:51 UTC, jwoodruff40 commented on A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
> +_veh setVehicleRadar (getNumber (configOf _veh >> "radarType") in [2,4]);
As it turns out, `setVehicleRadar` takes an int (0 for automatic, 1 for forced on, 2 for forced off) not a bool

```suggestion
_veh setVehicleRadar ([0, 1] select (getNumber(configOf _veh >> "radarType") in [2, 4]));
```

2025-11-08 17:58 UTC, wersal454 commented
<img width="886" height="276" alt="image" src="https://github.com/user-attachments/assets/229018cf-f581-4ca5-9b98-d982601a8c2e" />
this change throws errors at line 133

```
20:47:45 Error in expression <ase "turret": {
private _path = _x call BIS_fnc_turretPath;
if !(_path isEqualTo>
20:47:45   Error position: <BIS_fnc_turretPath;
if !(_path isEqualTo>
20:47:45   Error Undefined variable in expression: bis_fnc_turretpath
20:47:45 File x\A3A\addons\core\functions\Base\fn_updateRebelStatics.sqf..., line 133
20:47:45  ➥ Context: 	[] L128 (x\A3A\addons\core\functions\Base\fn_updateRebelStatics.sqf)
```

2025-11-08 18:12 UTC, wersal454 commented on A3A/addons/garage/Public/config.inc
> +		publicVariable "UngaragedVehicles";
Vehicles that are taken out of garage are not populated by AI by default (even when you leave the area and comeback), only vehicles bought from the store are. Ungaraged vehicles automatically get populated only after server restart.

Soo... so so

Maybe prevent auto-populating for bought vehicles?

2025-11-10 19:34 UTC, jwoodruff40 commented on A3A/addons/garage/Public/config.inc
> +		publicVariable "UngaragedVehicles";
Ah, I was looking in the wrong part of the code. Looks like you're right.

2025-11-11 11:03 UTC, UnseenKill commented on A3A/addons/garage/Public/config.inc
> +		publicVariable "UngaragedVehicles";
> <img alt="image" width="772" height="651" src="https://private-user-images.githubusercontent.com/29953387/507561568-58f0fa7c-613c-4577-8590-76b8f6b21993.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI4NDI5OTYsIm5iZiI6MTc2Mjg0MjY5NiwicGF0aCI6Ii8yOTk1MzM4Ny81MDc1NjE1NjgtNThmMGZhN2MtNjEzYy00NTc3LTg1OTAtNzZiOGY2YjIxOTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTExVDA2MzEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMjk1YzFhMDU4MGY0NDVhYWE4NGMxMjZhZDY4MjljZWVmNWMwMTBjZGI4N2MwNjBhZGVkOTlkZDIyMzUwYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YwdtwOz5UsBG2fG7PjlQXSmSy9vogRSJxwHAXYV7D_c"> Aren't we already doing that? I might remember it wrong.

The suggestion does the opposite from the screenshot: it locks anything _but_ static emplacements for AI until you unlock them.

2025-11-11 16:26 UTC, jwoodruff40 submitted a review, later dismissed
I believe [this](https://discord.com/channels/@me/1425526390761066588/1437526152473346090) was the last major holdup for this PR. Going to approve for merge back into public-testing. Testing there / in AUC will determine suitability for unstable / 11.8 inclusion.

2025-12-20 13:39 UTC, jwoodruff40 approved these changes
Approved subject to 718

2025-12-20 17:54 UTC, merged