Ef compatibility
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #403
Opened 2024-11-30 23:49 UTC by wersal454

## What type of PR is this?
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information:

ported and adapted templates from community #3441
also port of #3442

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

********************************************************
Notes:

2024-12-03 10:42 UTC, wersal454 commented
Also, don't forget about doing "prices" in Vehicle_Attributes

2024-12-03 22:12 UTC, wersal454 commented
Untested

Need to launch every template to check if there are any errors
Also need to check cargo config for the new turret

2024-12-04 15:10 UTC, SilenceIsFatto requested changes

2024-12-04 15:10 UTC, SilenceIsFatto commented on A3A/addons/logistics/Nodes/EF.hpp
> +};
This is already defined
```suggestion
```

2024-12-04 15:34 UTC, SilenceIsFatto requested changes
Double check the Vanilla_AI_XYZ templates as quite a few are missing the `private _hasEF = "ef" in A3A_enabledDLC;` declaration

2024-12-04 15:34 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Arid.sqf
> +#include "Vanilla_Vehicle_Attributes.sqf"
```suggestion
#include "..\Vanilla\Vanilla_Vehicle_Attributes.sqf"
```

2024-12-04 15:34 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Temperate.sqf
> +#include "Vanilla_Vehicle_Attributes.sqf"
This path doesn't exist
```suggestion
#include "..\Vanilla\Vanilla_Vehicle_Attributes.sqf"
```

2024-12-04 15:34 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Arid.sqf
> +["vehiclesHelisLightAttack", _helisLightAttack] call _fnc_saveToTemplate;
These variables did not exist
```suggestion
["vehiclesPolice", _vehiclesPolice] call _fnc_saveToTemplate;
["vehiclesHelisLightAttack", _vehiclesHelisLightAttack] call _fnc_saveToTemplate;
```

2024-12-04 15:34 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Arid.sqf
> +["vehiclesHelisAttack", _helisAttack] call _fnc_saveToTemplate;
```suggestion
["vehiclesHelisLight", _vehiclesHelisLight] call _fnc_saveToTemplate;
["vehiclesHelisAttack", _vehiclesHelisAttack] call _fnc_saveToTemplate;
```

2024-12-04 15:34 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Temperate.sqf
> +["vehiclesHelisLightAttack", _helisLightAttack] call _fnc_saveToTemplate;
```suggestion
["vehiclesPolice", _vehiclesPolice] call _fnc_saveToTemplate;
["vehiclesHelisLightAttack", _vehiclesHelisLightAttack] call _fnc_saveToTemplate;
```

2024-12-04 15:34 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Temperate.sqf
> +["vehiclesHelisAttack", _helisAttack] call _fnc_saveToTemplate;
```suggestion
["vehiclesHelisLight", _vehiclesHelisLight] call _fnc_saveToTemplate;
["vehiclesHelisAttack", _vehiclesHelisAttack] call _fnc_saveToTemplate;
```

2024-12-05 13:18 UTC, SilenceIsFatto requested changes
The 3 `Vanilla_AI_NATO_Side` templates are missing the `_gunBoat` variable used in DLC_content includes, should double check for any other variables missed

2024-12-05 14:23 UTC, SilenceIsFatto approved these changes
Lgtm

2024-12-05 15:10 UTC, merged