Patch 39
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #413
Opened 2024-12-08 23:29 UTC by wersal454

## What type of PR is this?
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement
4. [x] Miscellaneous

### What have you changed and why?
Information:

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

********************************************************
Notes:

2024-12-09 21:26 UTC, SilenceIsFatto requested changes

2024-12-09 21:26 UTC, SilenceIsFatto commented on A3A/addons/core/Params.hpp
> +    };
```suggestion
    class disableAutoSmokeCover
    {
        title = $STR_params_disableAutoSmokeCover;
        values[] = {0,1};
        texts[] = {$STR_antistasi_dialogs_generic_button_no_text, $STR_antistasi_dialogs_generic_button_yes_text};
        default = 0;
    };
```

2024-12-09 21:26 UTC, SilenceIsFatto commented on A3A/addons/core/functions/AI/fn_paradrop.sqf
> +                if !(disableSmokecoverauto) then {
```suggestion
                if !(disableAutoSmokeCover) then {
```

2024-12-09 21:26 UTC, SilenceIsFatto commented on A3A/addons/core/functions/AI/fn_smokeCoverAuto.sqf
> +if (disableSmokecoverauto) exitWith {};
```suggestion
if (disableAutoSmokeCover) exitWith {};
```

2024-12-09 21:26 UTC, SilenceIsFatto commented on A3A/addons/scrt/Stringtable.xml
> +            </Key>
```suggestion
            <Key ID="STR_params_disableAutoSmokeCover">
                <Original>Disable Auto Smoke Cover Script (Helps with performance)</Original>
                <Russian></Russian>
            </Key>
```

2024-12-09 21:35 UTC, wersal454 commented
![image](https://github.com/user-attachments/assets/e03602fb-ecf6-46c9-a303-daa972c59062)
![i-want-it-done-by-the-book-sergeant-harrison-yates](https://github.com/user-attachments/assets/bc97dbca-a992-4ce3-a85c-1d34521026c7)

2024-12-27 16:05 UTC, SilenceIsFatto commented
Should be ready for merge when changes are made

2024-12-28 09:45 UTC, wersal454 commented
done

2024-12-30 15:36 UTC, SilenceIsFatto approved these changes

2025-01-14 15:56 UTC, merged