SMGs to templates
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #419
Opened 2024-12-09 00:56 UTC by wersal454

## What type of PR is this?
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement
4. [x] Miscellaneous

### What have you changed and why?
Information:

replace rifles with SMGs in [selectRandom ["rifles", "carbines"]] call _fnc_setPrimary;
and
in some cases add SMGs to [selectRandom ["rifles", "carbines"]] call _fnc_setPrimary;

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

********************************************************
Notes:

2024-12-09 20:58 UTC, stutpip123 commented
its trying to merge into stable, should be directed into unstable.

have you verified that every single template you have changed actually uses SMGs, cause if not then its liable to break and pointless to change.
as the PR will need redoing anyway to point to unstable, perhaps start smaller focusing on templates where it makes the biggest difference and most logical usage of SMGs, don't just do it to all of them

2024-12-09 21:04 UTC, wersal454 commented
> its trying to merge into stable, should be directed into unstable.
> 
> have you verified that every single template you have changed actually uses SMGs, cause if not then its liable to break and pointless to change. as the PR will need redoing anyway to point to unstable, perhaps start smaller focusing on templates where it makes the biggest difference and most logical usage of SMGs, don't just do it to all of them

won't be needing to redoing the pr to switch into unstable, you simply change the base
As for verification, I'll take a look if every template has SMG's or not

2024-12-10 00:17 UTC, wersal454 commented
after the first pass, noticed that I missed a couple of templates, added changes to those
Checked every template, seems every affected template has them
+ some RHS and 3CB US templates don't have any SMGs AT ALL, so removed changes in them @SilenceIsFatto police still uses smgs in such templates(sometimes only SMGs) and it doesn't break(seemingly)

2025-10-29 02:01 UTC, jwoodruff40 requested changes
Please weight the primary types appropriately as was done before https://github.com/Antistasi-Ultimate-Community/A3-Antistasi-Ultimate/pull/540#issuecomment-2812493133

2025-10-31 00:09 UTC, jwoodruff40 requested changes
Ok, I was not about to review 178 files manually, so I wrote a python script instead to check if all these templates actually have carbines and SMGs.

We're good on carbines; however the following templates are missing SMGs, so need you to remove the changes from them, or if SMGs get selected then the AI just won't get a primary at all.

```
Templates missing smgs (total 32):

 - 3CBF_AI_ARD
 - 3CBF_AI_TKA
 - 3CBF_Riv_CHDKZ
 - 3CBF_Riv_CHDKZ_CW
 - 3CBF_Riv_TI
 - Aegis_Riv_CHDKZ
 - Vanguard_Riv_Replika
 - CSLA_Riv_Separatists
 - CUP_Riv_CHDKZ
 - CUP_Riv_LC_BOC
 - CW_Riv_DET
 - EMP_Riv_GP
 - WM_Riv_GP
 - CWR_Riv_ComMilitia
 - CWR_Riv_TReb
 - GM_Riv_VSBD
 - IFA_Riv_COMU
 - RACS_Riv_QB
 - RHS_Riv_CHDKZ
 - RHS_Riv_SZAVB
 - SPE_RIV_FFD
 - STALKER_Riv_Bandits
 - STALKER_Riv_Bandits_RHS
 - STALKER_Riv_Duty
 - STALKER_Riv_Duty_RHS
 - UNS_Riv_SVR
 - Vanilla_Riv_Exegermenos
 - Vanilla_Riv_LE
 - Vanilla_Riv_Remnants
 - VN_Riv_HM
 - VN_Riv_PL
 - WS_Riv_Exegermenos
```

2025-10-31 12:01 UTC, wersal454 commented
> Ok, I was not about to review 178 files manually, so I wrote a python script instead to check if all these templates actually have carbines and SMGs.
> 
> We're good on carbines; however the following templates are missing SMGs, so need you to remove the changes from them, or if SMGs get selected then the AI just won't get a primary at all.
> 
> ```
> Templates missing smgs (total 32):
> 
>  - 3CBF_AI_ARD
>  - 3CBF_AI_TKA
>  - 3CBF_Riv_CHDKZ
>  - 3CBF_Riv_CHDKZ_CW
>  - 3CBF_Riv_TI
>  - Aegis_Riv_CHDKZ
>  - Vanguard_Riv_Replika
>  - CSLA_Riv_Separatists
>  - CUP_Riv_CHDKZ
>  - CUP_Riv_LC_BOC
>  - CW_Riv_DET
>  - EMP_Riv_GP
>  - WM_Riv_GP
>  - CWR_Riv_ComMilitia
>  - CWR_Riv_TReb
>  - GM_Riv_VSBD
>  - IFA_Riv_COMU
>  - RACS_Riv_QB
>  - RHS_Riv_CHDKZ
>  - RHS_Riv_SZAVB
>  - SPE_RIV_FFD
>  - STALKER_Riv_Bandits
>  - STALKER_Riv_Bandits_RHS
>  - STALKER_Riv_Duty
>  - STALKER_Riv_Duty_RHS
>  - UNS_Riv_SVR
>  - Vanilla_Riv_Exegermenos
>  - Vanilla_Riv_LE
>  - Vanilla_Riv_Remnants
>  - VN_Riv_HM
>  - VN_Riv_PL
>  - WS_Riv_Exegermenos
> ```

- 3CBF_Riv_CHDKZ
 - 3CBF_Riv_CHDKZ_CW
 - 3CBF_Riv_TI
 - Aegis_Riv_CHDKZ
 - Vanguard_Riv_Replika
 - CUP_Riv_CHDKZ
 - CUP_Riv_LC_BOC
 - CW_Riv_DET
 - EMP_Riv_GP
 - WM_Riv_GP
don't have any code with SMG, so I guess your script is busted. - 3CBF_AI_ARD  - 3CBF_AI_TKA are fixed though.

2025-10-31 13:57 UTC, jwoodruff40 commented
Well the script didn't actually check if those templates were in this pr, it just checked every template

2025-10-31 16:44 UTC, jwoodruff40 approved these changes

2025-11-01 14:06 UTC, merged