WS&RF update
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #426
Opened 2024-12-21 18:21 UTC by wersal454

## What type of PR is this?
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement
4. [x] Miscellaneous

### What have you changed and why?
Information:

added content from recent CDLC's updates

+ "exclusive" pickup minigun variant
jk
thanks to Ravenholm from Aegis team for revealing this little tinitiny secret vehicle

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

********************************************************
Notes:

2024-12-22 11:58 UTC, wersal454 commented
I also added new vehicles to the blackmarket spreadsheet

2024-12-22 14:16 UTC, wersal454 commented
Reminder

need to add new vehicles to logistics
+ need to add nickel steel vehicles to logistics
+ need to add EF's LCC-1 to logistics

2024-12-23 03:26 UTC, wersal454 commented
ah, I forgot to add supply and medical vehicles to vanilla rebel templates

2024-12-27 16:25 UTC, SilenceIsFatto reviewed
I hope you've tested every single one of these files, because last time you made a pull this huge with similar changes it caused a CTD in 4 seperate cases

2024-12-29 03:17 UTC, wersal454 commented
loaded all of them(I think) made some fixes, should be fine

2025-01-24 21:04 UTC, wersal454 commented
https://docs.google.com/spreadsheets/d/1NwTr220tsjGuRghgNGttHunGPfvJX2sBUCAu9hL4f24/edit?usp=sharing

spreadsheet with all affected templates

2025-01-25 11:26 UTC, wersal454 commented
> https://docs.google.com/spreadsheets/d/1NwTr220tsjGuRghgNGttHunGPfvJX2sBUCAu9hL4f24/edit?usp=sharing
> 
> spreadsheet with all affected templates

tested every template, everything works

2025-01-25 11:28 UTC, wersal454 commented
But I spotted 1 bug/thing
![image](https://github.com/user-attachments/assets/d9a09a93-dacf-49ba-a466-c2a3afab5bba)

@jwoodruff40 I believe this is from your PR

2025-01-25 14:35 UTC, jwoodruff40 commented
> I spotted 1 bug/thing

Just to confirm what you're talking about, it's all the stuff being unlimited right?

2025-01-25 14:41 UTC, wersal454 commented
> > I spotted 1 bug/thing
> 
> Just to confirm what you're talking about, it's all the stuff being unlimited right?

nono
sorry, forgot to zoom in on the picture
I'm talking about stuff on the right side of the screen

This insignia thing + bipods are missing + magazine stuff you added is missing(not missing but it's in the other section for some reason)
I think it is caused by CUP or some cdlc, because when I load vanilla only, it looks fine

2025-01-25 14:46 UTC, jwoodruff40 commented
Ah I see now. Yeah that's weird. I'll take a look. I've never seen those insignia tabs before, but I suspect the issue has something to do with those.

Hopefully not from SPE bc that's the only cdlc I don't have

2025-01-25 15:53 UTC, wersal454 commented
> https://docs.google.com/spreadsheets/d/1NwTr220tsjGuRghgNGttHunGPfvJX2sBUCAu9hL4f24/edit?usp=sharing
> 
> spreadsheet with all affected templates

Khm

So, I tested all the templates
Then I noticed that I was playing current steam test version
good news everything works there

Then I switched to this PR build and noticed that SPE weapons are causing errors for LDF and AAF templates, so I had to comment most of that stuff out
error in question is on screenshot below
![image](https://github.com/user-attachments/assets/5dfd44dd-4915-42d2-af49-fd0a44298fe5)
![image](https://github.com/user-attachments/assets/a84e2a46-aaf6-453e-8a7d-f82a625d4d39)
![image](https://github.com/user-attachments/assets/bc6bd4eb-856a-49bc-b406-c423df71f835)
So if you going to continue working on weighed stuff, consider taking a look @PetMudstone and @martin509

2025-01-26 16:27 UTC, jwoodruff40 commented
@wersal454 I'm not seeing those issues with the arsenal when testing this PR. Also, not seeing any changes to the arsenal files whatsoever in this PR.

What mods / DLC were you using? Or did you find it was something else?

2025-01-26 16:51 UTC, wersal454 commented
> @wersal454 I'm not seeing those issues with the arsenal when testing this PR. Also, not seeing any changes to the arsenal files whatsoever in this PR.
> 
> What mods / DLC were you using? Or did you find it was something else?

![image](https://github.com/user-attachments/assets/25bb1175-bf9f-41af-83f5-47779724c916)
![image](https://github.com/user-attachments/assets/2719c990-5f78-45ae-a86f-6c0031851d03)

2025-01-26 17:03 UTC, SilenceIsFatto commented
At that point what *isn't* breaking something?

2025-01-26 17:21 UTC, wersal454 commented
> At that point what _isn't_ breaking something?

well, before "choosing mags in the arsenal" thing, it was fine)

2025-01-26 19:18 UTC, jwoodruff40 commented
So apparently, I *do* have SPE (must have bought it in a bundle and forgot...). But anyway turns out this is a SOGPF issue. I'm investigating further.

2025-01-26 19:56 UTC, jwoodruff40 commented
@wersal454 merge #449 and give that a test. Fixes the issue on my end.

2025-01-27 17:42 UTC, wersal454 commented
> @wersal454 merge #449 locally and give that a test. Fixes the issue on my end.

![image](https://github.com/user-attachments/assets/231e3c4a-b7af-4048-a2d8-1a62269b9b14)
yep, seems fine

2025-01-30 20:25 UTC, SilenceIsFatto requested changes
I would recommend ditching the `EnemyDetected` event handler spam. Don't just repeat code in literally every function you think it needs to be in, it's messy. 

At the very least make it a function so only one line needs to be changed. There might be event handler duplication here and I don't think I can approve of the EH changes anyway.

2025-01-30 20:25 UTC, Silence-112 commented on A3A/addons/core/Templates/Templates/#Examples/RebelExample.sqf
> +]] call _fnc_saveToTemplate; */ // not used anymore(?)
Correct, should just remove this entirely

2025-01-30 20:25 UTC, Silence-112 commented on A3A/addons/core/Templates/Templates/DLC_content/weapons/SPE/Vanilla_AAF.sqf
Can you clean this file up? A lot of commented code

2025-01-30 20:25 UTC, Silence-112 commented on A3A/addons/core/Templates/Templates/DLC_content/weapons/SPE/Vanilla_LDF.sqf
Same with this file, needs cleanup

2025-01-30 20:25 UTC, Silence-112 commented on A3A/addons/logistics/Nodes/Nickelsteel.hpp
It would be better to use model names here rather than absolute classnames, won't need as many classes that way

2025-01-30 20:25 UTC, Silence-112 commented on A3A/addons/logistics/Cargo/SPEX.hpp
> +class WW2_SPEX_addons_Assets_m_Weapons_Mortars_m_SPEX_M2_p3d : TRIPLES(ADDON,Cargo,Base) ///////fix it
"fix it"
Fix what?

2025-01-30 20:25 UTC, Silence-112 commented on A3A/addons/hals/Addons/store/config/spex.hpp
Are these helmets definitely added by SPEX and not SPE? I'd like to assume that they'd use the prefix SPE but I am often disappointed by reality

2025-01-30 20:25 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/WS/WS_AI_NATO&UNA.sqf
I would recommend diluting the _(XYZ)glammo arrays in all of the main template files to contain a smoke or flare if they don't already, don't assume players want to be bombarded by grenades that can't be countered

2025-01-30 20:25 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
> +["vehiclesMedical", _vehiclesMedical] call _fnc_saveToTemplate; //add here something
"//add here something"
Add what?

2025-01-30 21:15 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/DLC_content/weapons/SPE/Vanilla_AAF.sqf
this one, no

Not at this point, need to figure out what is wrong with those classnames, problem related is in my comment above

2025-01-30 21:15 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/DLC_content/weapons/SPE/Vanilla_LDF.sqf
same here

2025-01-30 21:19 UTC, wersal454 commented on A3A/addons/logistics/Nodes/Nickelsteel.hpp
somethingsomething, different vehicles have (visually) different cargo space but same model, so I HAD to use classnames

Same story was with vanilla UGVs

2025-01-30 21:22 UTC, wersal454 commented on A3A/addons/logistics/Cargo/SPEX.hpp
> +class WW2_SPEX_addons_Assets_m_Weapons_Mortars_m_SPEX_M2_p3d : TRIPLES(ADDON,Cargo,Base) ///////fix it
same as most comments in here, I left them for myself and forgot to delete them

2025-01-30 21:22 UTC, wersal454 commented on A3A/addons/hals/Addons/store/config/spex.hpp
If you would to trust arsenal icons, they come from SPEX

Most of the stuff that was added in SPEX were helmets)

2025-01-30 21:25 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_NATO&UNA.sqf
arrays contain exactly what was previously there (so yeah, they do contain some smoke and flare stuff)

I replaced stuff with arrays in order to add stuff in future if there will be any new interesting grenades

2025-01-30 21:38 UTC, wersal454 commented
> I would recommend ditching the `EnemyDetected` event handler spam. Don't just repeat code in literally every function you think it needs to be in, it's messy.
> 
> At the very least make it a function so only one line needs to be changed. There might be event handler duplication here so I don't think I can approve of the EH changes anyway.

EnemyDetected EH is not used anywhere I think, but yeah changing it to function is a better way

About spamming, don't think so, because different spawn functions use different "init" functions, so despite what function spawned the bot, it will use event handler

by different spawn functions I mean rebel AI and enemy AI 
or AI that are used in QRFs are using one "init" while garrison AI for example uses another

2025-01-30 21:39 UTC, wersal454 commented
> > I would recommend ditching the `EnemyDetected` event handler spam. Don't just repeat code in literally every function you think it needs to be in, it's messy.
> > At the very least make it a function so only one line needs to be changed. There might be event handler duplication here so I don't think I can approve of the EH changes anyway.
> 
> EnemyDetected EH is not used anywhere I think, but yeah changing it to function is a better way
> 
> About spamming, don't think so, because different spawn functions use different "init" functions, so despite what function spawned the bot, it will use event handler
> 
> by different spawn functions I mean rebel AI and enemy AI or AI that are used in QRFs are using one "init" while garrison AI for example uses another

For this one I think, it ACTUALLY would be better to move it to separate PR, so we could study it better

2025-02-01 14:02 UTC, Silence-112 commented on A3A/addons/core/functions/CREATE/fn_RivalsCreateUnit.sqf
> +	};
Shouldn't these be removed by your last commit?
It's still in a few files

2025-02-02 00:19 UTC, wersal454 commented on A3A/addons/core/functions/CREATE/fn_RivalsCreateUnit.sqf
> +	};
huh, I guess, I missed it

2025-02-02 13:35 UTC, wersal454 commented
> > > I would recommend ditching the `EnemyDetected` event handler spam. Don't just repeat code in literally every function you think it needs to be in, it's messy.
> > > At the very least make it a function so only one line needs to be changed. There might be event handler duplication here so I don't think I can approve of the EH changes anyway.
> > 
> > 
> > EnemyDetected EH is not used anywhere I think, but yeah changing it to function is a better way
> > About spamming, don't think so, because different spawn functions use different "init" functions, so despite what function spawned the bot, it will use event handler
> > by different spawn functions I mean rebel AI and enemy AI or AI that are used in QRFs are using one "init" while garrison AI for example uses another
> 
> For this one I think, it ACTUALLY would be better to move it to separate PR, so we could study it better

Moved it to #454

2025-02-02 15:00 UTC, wersal454 commented
checked problem with SPE, all classnames are right, don't what's causing the problem

2025-02-02 20:48 UTC, SilenceIsFatto reviewed
Will need to be double checked ingame, but seems fine

2025-02-03 21:15 UTC, martin509 commented
> checked problem with SPE, all classnames are right, don't what's causing the problem

Quickly butting in, from what I see the AAF config is fine but you put item weights on the LDF config without adding item weights to the baseline vanilla config. Remove the item weights and it should be fine.

2025-02-03 21:24 UTC, wersal454 commented
> > checked problem with SPE, all classnames are right, don't what's causing the problem
> 
> Quickly butting in, from what I see the AAF config is fine but you put item weights on the LDF config without adding item weights to the baseline vanilla config. Remove the item weights and it should be fine.

Yeah, copypasted stuff from AAF to LDF without second thought

But, both AAF weighted and LDF unweighted SPE content doesn't work and errors with that weird error

2025-02-04 12:37 UTC, jwoodruff40 commented
Are you going to add the [CSLA 1.2 update](https://arma3.com/news/arma-3-creator-dlc-csla-iron-curtain-update-12) stuff to this PR as well?

2025-02-04 12:40 UTC, wersal454 commented
> Are you going to add the [CSLA 1.2 update](https://arma3.com/news/arma-3-creator-dlc-csla-iron-curtain-update-12) stuff to this PR as well?

I'm finishing up with "new" CSLA factions, but I haven't touched any of the new content itself

2025-02-04 15:39 UTC, wersal454 commented
updated CSLA templates + added new desert factions

2025-02-04 16:11 UTC, wersal454 commented
Things left to do with CSLA update:
logistics for new vehicles
store
black market
no insignia variants for the new vehicles
new content for vanilla factions

2025-02-05 17:10 UTC, wersal454 commented
added new vehicles and noinsignia variants to the spreadsheet

2025-02-05 22:38 UTC, wersal454 commented
added new csla content to vanilla

2025-02-12 23:56 UTC, SilenceIsFatto requested changes
Have you retested affected templates and the new CSLA stuff?

Also this is the last PR I will review that is either:

A: Absurdly huge without any *actual* additions
B: Affiliated with the MOD_content/DLC_content system
C: A bunch of code that isn't tested and isn't marked as a draft

All of these things, especially when mixed together, make it impossible to review **efficiently** and **properly** which results in things like the 11.4.1 CTD issues that were missed

2025-02-12 23:56 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/DLC_content/weapons/CSLA/Vanilla_AAF.sqf
> +    ["US85_M60E3SB","","","US85_ANPVS4_M60",["US85_100Rnd_762x51","US85_100Rnd_762x51","US85_100Rnd_762x51"],[],""],
No weights?

2025-02-12 23:56 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT&SFIA.sqf
> +	#include "..\MOD_content\Nickelsteel\weapons\Vanilla_CSAT&AAF.sqf"
Should this be including content from CSAT&AAF?

2025-02-12 23:56 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO&AAF.sqf
> +	#include "..\MOD_content\Nickelsteel\vehicles\Vanilla_AAF.sqf"
Should this be including AAF or NATO&AAF?

2025-02-12 23:56 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/CSLA/CSLA_AI_AFMC.sqf
> +    ["US85_M60E3SB", "", "", "US85_ANPVS4_M60", ["US85_100Rnd_762x51","US85_100Rnd_762x51","US85_100Rnd_762x51"], [], ""],
```suggestion
    ["US85_M60E3SB", "", "", "US85_ANPVS4_M60", ["US85_100Rnd_762x51","US85_100Rnd_762x51","US85_100Rnd_762x51"], [], ""]
```

2025-02-12 23:56 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/CSLA/CSLA_AI_AFMC.sqf
> +    ["US85_M60E3SB", "", "", "US85_ANPVS4_M60", ["US85_100Rnd_762x51","US85_100Rnd_762x51","US85_100Rnd_762x51"], [], ""],
```suggestion
    ["US85_M60E3SB", "", "", "US85_ANPVS4_M60", ["US85_100Rnd_762x51","US85_100Rnd_762x51","US85_100Rnd_762x51"], [], ""]
```

2025-02-12 23:56 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/CSLA/CSLA_AI_AFMC.sqf
> +    ["MEDIbackpacks"] call _fnc_setBackpack;
MEDIbackpacks does not exist

2025-02-12 23:56 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/CSLA/CSLA_AI_CSLA.sqf
> +    ["MEDIbackpacks"] call _fnc_setBackpack;
Doesn't exist

2025-02-12 23:56 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/CSLA/CSLA_AI_CSLA.sqf
> +    ["SNIvests"] call _fnc_setVest;
```suggestion
    ["sniVests"] call _fnc_setVest;
```
Change the rest of the SNIvests references accordingly, given that hashmap lookups are probably case sensitive

2025-02-13 00:48 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO&AAF.sqf
> +	#include "..\MOD_content\Nickelsteel\vehicles\Vanilla_AAF.sqf"
AAF

2025-02-13 00:49 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT&SFIA.sqf
> +	#include "..\MOD_content\Nickelsteel\weapons\Vanilla_CSAT&AAF.sqf"
Yes

2025-02-14 10:06 UTC, wersal454 commented
> Have you retested affected templates and the new CSLA stuff?
> 
> Also this is the last PR I will review that is either:
> 
> A: Absurdly huge without any _actual_ additions B: Affiliated with the MOD_content/DLC_content system (It's literally impossible to maintain, it should NOT be worked on further) C: A bunch of code that isn't tested and isn't marked as a draft
> 
> All of these things, especially when mixed together, make it impossible to review **efficiently** and **properly** which results in things like the 11.4.1 CTD issues that were missed

I'll retest everything later today, just to make sure

2025-02-17 17:54 UTC, wersal454 commented
> > Have you retested affected templates and the new CSLA stuff?
> > Also this is the last PR I will review that is either:
> > A: Absurdly huge without any _actual_ additions B: Affiliated with the MOD_content/DLC_content system (It's literally impossible to maintain, it should NOT be worked on further) C: A bunch of code that isn't tested and isn't marked as a draft
> > All of these things, especially when mixed together, make it impossible to review **efficiently** and **properly** which results in things like the 11.4.1 CTD issues that were missed
> 
> I'll retest everything later today, just to make sure

Didn't happen that day

But I retested every template + CSLA ones, everything works

2025-02-17 23:28 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
> +        _x params ["_sside", "_btype", "_starg", "_endtime", "_dur", "_pow"]; /// why _sside ?
Putting this question in a comment won't magically grant you the answer

In this case, probably means _supportSide. Take this as a shining example of why you should name variables properly!

2025-02-17 23:51 UTC, wersal454 commented on A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
> +        _x params ["_sside", "_btype", "_starg", "_endtime", "_dur", "_pow"]; /// why _sside ?
couldn't it be a typo?
![image](https://github.com/user-attachments/assets/19f1de8e-d1b8-47e9-816c-b4ae108f73d7)
I'm came up with this question because I encountered an error saying ```_sside``` is not defined

2025-02-17 23:56 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
> +        _x params ["_sside", "_btype", "_starg", "_endtime", "_dur", "_pow"]; /// why _sside ?
Has it always been like that?

2025-02-18 00:02 UTC, wersal454 commented on A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
> +        _x params ["_sside", "_btype", "_starg", "_endtime", "_dur", "_pow"]; /// why _sside ?
> Has it always been like that?

Last change was by Socrates over 2 years ago

2025-02-19 13:13 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
> +        _x params ["_sside", "_btype", "_starg", "_endtime", "_dur", "_pow"]; /// why _sside ?
`A3A_supportStrikes pushBack [_side, ...]`

2025-02-19 13:38 UTC, SilenceIsFatto reviewed
Vanilla templates load without issues, need a review of the CSLA templates from someone who has it (@stutpip123 ?)

2025-02-21 14:50 UTC, SilenceIsFatto commented on A3A/addons/core/Templates/Templates/CSLA/CSLA_AI_CSLA.sqf
> +    ["SNIvests"] call _fnc_setVest;
@wersal454 did you update every instance of SNIvests?

2025-02-21 15:10 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/CSLA/CSLA_AI_CSLA.sqf
> +    ["SNIvests"] call _fnc_setVest;
...
no

probably

I'll recheck it

2025-02-21 15:12 UTC, stutpip123 commented
> Vanilla templates load without issues, need a review of the CSLA templates from someone who has it (@stutpip123 ?)

CSLA templates load and work fine. Although the use of vanilla planes perhaps we should investigate retextures to be more era appropriate, the CSAT hex camo is really off putting

2025-02-21 15:14 UTC, wersal454 commented
> > Vanilla templates load without issues, need a review of the CSLA templates from someone who has it (@stutpip123 ?)
> 
> CSLA templates load and work fine. Although the use of vanilla planes perhaps we should investigate retextures to be more era appropriate, the CSAT hex camo is really off putting

Welp, that what they did in official CLSA antistasi mod

2025-02-21 15:16 UTC, stutpip123 commented
> > > Vanilla templates load without issues, need a review of the CSLA templates from someone who has it (@stutpip123 ?)
> > 
> > 
> > CSLA templates load and work fine. Although the use of vanilla planes perhaps we should investigate retextures to be more era appropriate, the CSAT hex camo is really off putting
> 
> Welp, that what they did in official CLSA antistasi mod

it is perfectly functional and playable, but a reskin would be the finishing touch. the US plane can mostly get away with it as its not too dissimilar to real and past A-10 paintjobs

2025-02-21 18:40 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/CSLA/CSLA_AI_CSLA.sqf
> +    ["SNIvests"] call _fnc_setVest;
I think it should be done now

2025-02-22 23:39 UTC, SilenceIsFatto approved these changes
The CSLA planes have room for improvement but that's for another time and/or pull

Overall, looks fine

2025-02-24 10:03 UTC, merged