Improve Rebel Primary Weapon Selection
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #427
Opened 2024-12-25 06:22 UTC by jwoodruff40

## What type of PR is this?
1. [ ] Bug
2. [X] Change
3. [X] Enhancement
4. [ ] Miscellaneous

### What have you changed and why?
Information: 

**Why:**

It was bothering me that when you start to accumulate / unlock better weapons in your arsenal, AI Rebels will just randomly 'pick' any weapon in a given category, instead of trying to 'pick' a better weapon. E.g. when playing as 3CB FIA, my rebels will quite often be equipped with M1 Garands (initial equipment) even when I have M16s, AK74s, AK105s, etc unlocked. This severely limits the Rebels' firepower compared to enemy AI.

I also noticed that fn_generateRebelGear / the A3A_rebelGear it creates is structured as a weighted list but doesn't currently make use of weights, adding everything with a weight of 1.

**What:**

This update to fn_generateRebelGear calculates a weaponWeight for each primary weapon added to A3A_rebelGear based on the weapon's attributes (positive and negative):

Positive attributes (higher is better):

 - accuracy
 - rate of fire
 - magazine capacity
 - 'impact force'
 
Negative attributes (higher is worse):

 - weight

It's heavily inspired by the weapon statistics shown in ACE3 Arsenal (especially the impact attribute), but the only code copied from ACE is the impact force calculation, a combination of muzzle velocity and bullet / ammo damage.

The end state is that when AI rebels are equipped, they'll be much more likely to equip better weapons, without entirely precluding use of 'lower tier' weapons. To that end, I attempted to weigh the weapon attributes sensibly.

Example weapon weights from a pretty new save (not very many weapons) with 3CB FIA vs 3CB AAF (some output omitted):

`A3A_rebelGear;` ==> 

```
[
[["GrenadeLaunchers",[
    "UK3CB_M16A2_UGL",40
]],
["MissileLaunchersAA",[
    "rhs_weap_fim92",
    "UK3CB_Blowpipe"
]],
["Shotguns",[
    "rhs_weap_M590_5RD",7
]],
["SniperRifles",[
    "UK3CB_Enfield",10,
    "UK3CB_M1903A1",3
]],
["Rifles,[
    "rhs_weap_m1garand_sa43",16,
    "rhs_weap_ak74m",45,
    "UK3CB_M16A2",47,
    "UK3CB_HK33KA1",40,
    "UK3CB_HK33KA3",40,
    "rhs_weap_ak105",53
]],
["SMGs",["rhs_weap_m3a1",53]]
]
```

### Please specify which Issue this PR Resolves (If Applicable).
None as far as I'm aware.

### Please verify the following.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [X] Yes (Please provide further detail below.)

Modification has only been tested with RHS and 3CBF factions / weapons, with a few randomly picked selections of test weapons and on a couple save files that use those factions. Needs more testing to ensure compatibility across other supported factions / weapon mods. I would also be interested in expanding to include weighing launchers and potentially other items, but need feedback on if that's wanted and what stats would make sense to weigh those items. 

### How can the changes be tested?
Steps:

Best way to test is probably to get a bunch of people running different factions and such to copy their save(s), load the copied save, and in the debug console input `A3A_rebelGear;`  and analyze the output for discrepancies, weapons whose stats / weight weren't properly identified / calculated, or if the weights seem to be either too close or too disparate strongly favoring certain weapons or not.

********************************************************
Notes:

I wanted to include weapon max range (or max effective range?) as an additional attribute, but I found that at least for RHS weapons the most ideal attributes to use (_config >> maxRange / _config >> maxRangeProbab) are generally all the same in the weapon config root, and are only updated under the fire modes, but a lot of RHS weapons use several custom fire modes instead of the normal "SINGLE" or "BURST" or "FULLAUTO", and I didn't want to have to iterate through all fire modes to attempt to find the best values like is done in ACE. Ultimately I decided that the impact force alone should be sufficient, given that generally, longer range weapons have higher muzzle velocity / larger bullets - the same things that affect impact force. May be worth revisiting though.

2024-12-25 07:00 UTC, jwoodruff40 commented
Another thought I had – I don't play with unlocks disabled, but for those that do, the amount of each weapon in the arsenal could also be included in the weapon weight calculation such that AI will be more likely to be equipped with weapons the rebels have more of, all else being equal.

2024-12-25 08:52 UTC, wersal454 commented
That looks really nice

For those who play with unlocks disabled, system I think should be adapted yes(if you can figure it out ofc)

Also maybe add a weights for secondary weapons(i.e. launchers)? Not sure how to qualify some launchers to be better then others, but maybe take a look at it
also I want to add handguns in #418, so maybe weights system for them as well?

2024-12-25 12:41 UTC, SilenceIsFatto commented
The base branch should be unstable rather than stable, changing it may cause merge conflicts so be aware of those

2024-12-25 14:46 UTC, wersal454 commented
just in case

Click "Edit" and this menu will pop up
![image](https://github.com/user-attachments/assets/084dacc3-ddf7-4000-9fe2-60b2bd9ee183)
there you can select different base branch

2024-12-25 21:54 UTC, jwoodruff40 commented
Thanks team for the input. I changed the base branch.

I have some thoughts on how to go about weighing other item types, but don't want to get too into the weeds lest it starts becoming too much of a subjective / playstyle-dependent approach. More to follow.

Merry Christmas / happy holidays to all and thanks for the awesome mod!

2024-12-26 02:16 UTC, jwoodruff40 commented
I fixed my rookie mistake of changing the param order for _fnc_addItem  and did some initial rework of the existing code for less code reuse.

Also pushed an initial implementation for _fnc_addItemNoUnlocks. It uses the already existing linearconversion of amount of item to range between 0 and 1 as a scalar for the item weight variable. So items with similar weight will be selected more often if there are more of them, and vice versa. Should make for some interesting results with varying item weights and amounts. 

Personally, I think that's a good enough implementation, but I don't ever play with unlocks disabled, so we could use some input from the crowd that do.

2024-12-26 04:33 UTC, jwoodruff40 commented
Refactored / generalized function to support whatever item types we want to implement custom weight / preference calculation for (secondaries, handguns, armor, etc).

2024-12-26 06:31 UTC, UAC-MaxxLite commented
I would also suggest that you limit the type of secondaries for each class if possible I.e. 
only AT and AA units being able to use guided launchers.
And disable secondary use for marksman medic and such.

This will make it harder for players that spam launchers on all types of units which just makes the game easier.

2024-12-26 07:55 UTC, jwoodruff40 commented
@UAC-MaxxLite that's done already in fn_equipRebel unless I'm misunderstanding what you mean. If you mean restricting players from override the AI loadouts with that kind of thing, I get what you mean. Not sure if that's in the scope of this PR or not though.

In any case, latest commit implements specific weight calculations for sniper rifles, rocket launchers (LAT), and handguns (per @wersal454 's suggestion / PR). How and why the attributes are weighted the way they are for those is commented in the file, but as stated before, definitely needs a lot of testing across supported mod sets.

2024-12-27 01:29 UTC, wersal454 commented
> I would also suggest that you limit the type of secondaries for each class if possible I.e. only AT and AA units being able to use guided launchers. And disable secondary use for marksman medic and such.
> 
> This will make it harder for players that spam launchers on all types of units which just makes the game easier.

restricting players from equipping any AI with launchers would take A TON of work, it would require changing arsenal code(probably) which is a bitch

2024-12-30 15:41 UTC, SilenceIsFatto reviewed
Looks fine, can be tested when you feel it ready

2024-12-31 07:06 UTC, jwoodruff40 commented
Pushed a few more fixes and things. I would call it ready for testing now. Can't (or don't know how) to set that label myself.

In summary (things to look for with testing the code), this PR does two main things:
 - Makes rebel forces (personal and HC squads) more likely to equip better weapons in each category, while still maintaining a equipping a variety of weaponry
 - Equips some rebel rifleman (percentage increases by war level) with disposable AT launcher

And sets the conditions for crafting interesting weights for other item types in the future - e.g. preferencing vests by some combination of weight, load capacity, armor value. 

---

Also going to push a larger refactor of `fn_generateRebelGear` following this comment. Intent was to remove a lot of the duplicate code between item types. Understand code style is very subjective and how it is now is probably more readable (if much more verbose), so can revert if not wanted.

2025-01-06 14:58 UTC, SilenceIsFatto reviewed
We'll try to test this in our next server campaign, will help bring any potential issues to light

2025-01-10 15:24 UTC, Silence-112 requested changes
Testing this locally reveals that no AI will actually get weapons due to errors, even Petros doesn't get given a weapon or vest. 

I would assume this is due to the fact that the _rebelGear hashmap never has any data set to it anymore, including no ArmoredVests/ArmoredHeadgear

```sqf
15:18:53 Error in expression <A_rebelGear get "ArmoredHeadgear");
if (_helmet == "") then { _helmet = selectRa>
15:18:53   Error position: <_helmet == "") then { _helmet = selectRa>
15:18:53   Error Undefined variable in expression: _helmet
15:18:53 File x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf..., line 96
15:18:53  ➥ Context: 	[] L35 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L36 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L108 (x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf)

15:18:53 Error in expression <
private _compatItems = compatibleItems _weapon; 
_compatOptics = _compatItems a>
15:18:53   Error position: <_weapon; 
_compatOptics = _compatItems a>
15:18:53   Error Undefined variable in expression: _weapon
15:18:53 File x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf..., line 66
15:18:53  ➥ Context: 	[] L35 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L36 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L111 (x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf)
	[] L116 (x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf)
	[] L65 (x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf)
	[] L67 (x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf)
	[] L68 (x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf)

15:18:53 Error in expression <ol = A3A_rebelGear get _weaponType;
if (_pool isEqualTo []) then {
_pool = A3A_r>
15:18:53   Error position: <_pool isEqualTo []) then {
_pool = A3A_r>
15:18:53   Error Undefined variable in expression: _pool
15:18:53 File x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf..., line 24
15:18:53  ➥ Context: 	[] L35 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L36 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L111 (x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf)
	[] L116 (x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf)
	[] L65 (x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf)
	[] L67 (x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf)
	[] L68 (x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf)

15:18:53 Error in expression <A3A_rebelGear get "OpticsClose";
};
if (_compatOptics isEqualTo []) then {
_comp>
15:18:53   Error position: <_compatOptics isEqualTo []) then {
_comp>
15:18:53   Error Undefined variable in expression: _compatoptics
15:18:53 File x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf..., line 72
15:18:53  ➥ Context: 	[] L35 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L36 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L111 (x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf)
	[] L116 (x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf)
	[] L65 (x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf)
	[] L78 (x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf)

15:18:53 Error in expression <he set [_weapon, _compatOptics];
};
if (_compatOptics isNotEqualTo []) then { _u>
15:18:53   Error position: <_compatOptics isNotEqualTo []) then { _u>
15:18:53   Error Undefined variable in expression: _compatoptics
15:18:53 File x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf..., line 80
15:18:53  ➥ Context: 	[] L35 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L36 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L111 (x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf)
	[] L116 (x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf)
	[] L80 (x\A3A\addons\core\functions\Ammunition\fn_randomRifle.sqf)

15:18:53 Error in expression <eighted (A3A_rebelGear get "NVGs");
if (_nvg != "") then { _unit linkItem _nvg }>
15:18:53   Error position: <_nvg != "") then { _unit linkItem _nvg }>
15:18:53   Error Undefined variable in expression: _nvg
15:18:53 File x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf..., line 222
15:18:53  ➥ Context: 	[] L35 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L36 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L241 (x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf)
```

2025-01-10 17:33 UTC, jwoodruff40 commented
> Testing this locally reveals that no AI will actually get weapons due to errors, even Petros doesn't get given a weapon or vest.
> 
> I would assume this is due to the fact that the _rebelGear hashmap never has any data set to it anymore, including no ArmoredVests/ArmoredHeadgear

Not to be the developer that says "it works for me, must be a you problem" at all, but.. I'm not getting any errors and it seems to work fine with no mods loaded except A3U built with this PR, CBA, and ace. But if we can't figure it out, we can just revert https://github.com/SilenceIsFatto/A3-Antistasi-Ultimate/pull/427/commits/46c81fa3923aa0dd4078ea4c10800b6debe378f0.

---

The gist of the refactor is that all instances of a code block like this:

```
private _itemType = []; // internal array
{
    _item = _x;
    <do some stuff>
    if (condition) then { _itemType append [_item, _itemWeight] } ; // add the item to the internal array
} forEach _items;

_rebelGear set ["Item Type", _itemType, true]; // set the hashmap from the pre-populated internal array
```

are instead replaced with:

```
// instead of using an internal array and pushing it to the hashmap when we're done, push directly to the hashmap
// if the item type doesn't yet exist in the hashmap, add an empty array
private _itemType = _rebelGear getOrDefault ["Item Type", [], true];
{
    _item = _x;
    <do some stuff>
    if (condition) then { _itemType append [_item, _itemWeight] } ; // add the item directly to the hashmap array
} forEach _items;
```

In short - `_rebelGear set XXX` is replaced with `_rebelGear getOrDefault [XXX, [], true]`.  `setDefault` param `true` creates the hashmap entry. See [getOrDefault](https://community.bistudio.com/wiki/getOrDefault)

2025-01-11 21:17 UTC, SilenceIsFatto reviewed
Works as expected now, seems to be much better than the previous system.

It'd be nice if A3A_rebelGear could be re-evaluated as you unlocked things rather than once you load a save, but I imagine there is a reason this is done once during init.

Regardless, looks fine now. I'll do a bit more testing with the obscure modsets like OPTRE and if it works then this should be fine for merge

2025-01-11 21:44 UTC, jwoodruff40 commented
> It'd be nice if A3A_rebelGear could be re-evaluated as you unlocked things rather than once you load a save, but I imagine there is a reason this is done once during init.

fn_generateRebelGear updates A3A_rebelGear and is called by fn_resourceCheck once on server init and every 10 minutes thereafter (fn_initServer line 276).

Afaict, there's no issues with calling it whenever you want as server admin.

It should be easily possible to *also* call generateRebelGear anytime an item is either unlocked (unlocks enabled) or quantity surpasses ITEM_MIN (no unlocks).

2025-01-11 21:52 UTC, SilenceIsFatto approved these changes
Was thinking of when things transfer to the arsenal but with the resourceCheck loop that would be redundant

It's much better with vanilla, seems to be better with OPTRE and works fine with spearhead 1944. I think it's fine for merge

2025-01-14 15:57 UTC, merged