More vehicle variety in convoy mission
Antistasi-Ultimate-Community/A3-Antistasi-Ultimate pull request #428
Opened 2024-12-27 01:26 UTC by wersal454

## What type of PR is this?
1. [ ] Bug
2. [x] Change
3. [x] Enhancement
4. [x] Miscellaneous

### What have you changed and why?
Information:

replaced AA vehicle with randomization with vehiclesArmor (i.e. it can be tank, apc, light tank, etc.)

now troops trucks can be militia or regular military depending on the war level

also lead vehicle can be militia or military depending on the war level

added repair type of convoy 

### Please specify which Issue this PR Resolves (If Applicable).
"This PR closes #XXXX!"

### Please verify the following.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?

1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

********************************************************
Notes:

2025-01-09 18:20 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +); ///maybe a proper war level check?
Maybe something like this?

```
private _typeVehX = selectRandom ( switch true do {
    case (_sideX == Occupants && random 4 < tierWar): { (_faction get "vehiclesPolice") };
    case (tierWar < 5): { (_faction get "vehiclesMilitiaLightArmed") };
    case (tierWar < 7): { (_faction get "vehiclesLightArmed") + (_faction get "vehiclesMilitiaLightArmed") };
    default { (_faction get "vehiclesLightArmed") };
});
```

It's doing the same thing, in half the lines and without all the nesting (of course, I'm also guilty of generally nesting a lot...)

2025-01-09 18:21 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +        };)
Similar to comment below...

```
_typeVehObj = selectRandom ( switch true do {
            case (tierWar < 5): { (_faction get "vehiclesMilitiaTrucks") };
            case (tierWar < 7): { (_faction get "vehiclesMilitiaTrucks") + (_faction get "vehiclesTrucks") };
            default { (_faction get "vehiclesTrucks") };
        });
```

2025-01-09 18:21 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +        };)
Similar to comment below...

```
_typeVehObj = selectRandom ( switch true do {
            case (tierWar < 5): { (_faction get "vehiclesMilitiaTrucks") };
            case (tierWar < 7): { (_faction get "vehiclesMilitiaTrucks") + (_faction get "vehiclesTrucks") };
            default { (_faction get "vehiclesTrucks") };
        });
```

2025-01-09 18:22 UTC, jwoodruff40 commented
Left a couple of suggestions - I'm working on a similar PR that makes money and supplies convoys more faction appropriate, so wanted to get this one to stop throwing script errors

2025-01-10 01:38 UTC, wersal454 commented
yeah, always forget that switch exists, that will do

2025-01-11 14:58 UTC, SilenceIsFatto reviewed
I assume that you plan on merging [#30](https://github.com/wersal454/A3-Antistasi/pull/30)?

2025-01-11 14:58 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +        _vehiclePool = append [_supplyVehicles,_medicalVehicles];
`append [array, array]`?

Append works by appending one array to another, e.g `array1 append array2`

What I assume you want here is
```suggestion
        _vehiclePool = (_supplyVehicles + _medicalVehicles);
```

2025-01-11 14:58 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +    waitUntil {sleep 1; (time > _timeout) or (_vehObj distance _posDest < _arrivalDist) or (not alive _vehObj) or (side group driver _vehObj != _sideX)};
Have you tried lazy evaluation here? Would probably be better scheduling wise

Example
```suggestion
    waitUntil {sleep 1; (time > _timeout) || {(_vehObj distance _posDest < _arrivalDist) or (not alive _vehObj) or (side group driver _vehObj != _sideX)}};
```

2025-01-11 14:58 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +private _sideshort =  if (sidesX getVariable [_mrkOrigin,sideUnknown] == Occupants) then {occ} else {inv};
occ/inv only exist in the FactionGet macros, no?

```sqf
#define FactionGet(FAC, VAR) (A3A_faction_##FAC get VAR)
```

Also isn't this redundant given _sideX and _faction are already defined, so you can just use `_faction get "XYZ"`?

```suggestion
```

2025-01-11 14:58 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +        _typeVehObj = selectRandom (FactionGet(_sideshort, "vehiclesArmor"));
```suggestion
        _typeVehObj = selectRandom (_faction get "vehiclesArmor");
```

2025-01-25 14:59 UTC, SilenceIsFatto reviewed
How much has this been tested? Just curious if you've observed any potential problems with edge cases

2025-01-25 14:59 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +        _vehiclePool = if _civDisabled then { _milFaction get "vehiclesMilitiaTrucks" } else { _civFaction get "vehiclesCivIndustrial" } select { typeName _x == "STRING"}; // * convert weighted list
```suggestion
        _vehiclePool = if (_civDisabled) then { _milFaction get "vehiclesMilitiaTrucks" } else { _civFaction get "vehiclesCivIndustrial" } select { typeName _x == "STRING"}; // * convert weighted list to normal array
```

2025-01-25 14:59 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +        _vehiclePool = if _civDisabled then { _milFaction get "vehiclesMilitiaTrucks" } else { _civFaction getOrDefault ["vehiclesCivMedical", _civFaction get "vehiclesCivIndustrial"] } select { type
```suggestion
        _vehiclePool = if (_civDisabled) then { _milFaction get "vehiclesMilitiaTrucks" } else { _civFaction getOrDefault ["vehiclesCivMedical", _civFaction get "vehiclesCivIndustrial"] } select { typeName _x == "STRING"}; // * convert weighted list to normal array
```
Does the else statement (`_civFaction getOrDefault ["vehiclesCivMedical", _civFaction get "vehiclesCivIndustrial"]`) actually work? Shouldn't this be `+` instead of `,`?

2025-01-25 14:59 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +                break
Are the `break` and `continue` here really necessary? I can see why the break might be used, but isn't the continue redundant?

2025-01-25 15:14 UTC, jwoodruff40 commented
> How much has this been tested? Just curious if you've observed any potential problems with edge cases

...minimally. It needs testing to ensure all types still work as normal. The only ones I actually semi-tested while iterating were the money and supplies ones; however, I know of two issues that need solved before merge:

 - [ ] Wobbling money crates (see my comment in Wersal's repo)
 - [ ] I don't think I updated the code that deletes / despawns the objective to delete the money crates. I think it will just delete the pallet they sit on, but this will become a non-issue if we have to just load one crate to fix the first issue.

2025-01-25 15:25 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +        _vehiclePool = if _civDisabled then { _milFaction get "vehiclesMilitiaTrucks" } else { _civFaction get "vehiclesCivIndustrial" } select { typeName _x == "STRING"}; // * convert weighted list
Lgtm; I can't accept the suggestion bc not my PR anymore lol.

I did read on the Arma 3 optimization guide that `select { _x isEqualType "" }` should be significantly faster than `select { typeName _x == "STRING" }` so may be worthwhile to make that change here as well. Or not, idk. probably doesn't realistically make much of a difference.

2025-01-25 15:31 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +        _vehiclePool = if _civDisabled then { _milFaction get "vehiclesMilitiaTrucks" } else { _civFaction getOrDefault ["vehiclesCivMedical", _civFaction get "vehiclesCivIndustrial"] } select { type
It's just an admittedly confusing way to rewrite:

```
_vehiclePool = if (_civDisabled) then {
    _milFaction get "vehiclesMilitiaTrucks"}
else {
    if !(isNil _civFaction get "vehiclesCivMedical") then {
        _civFaction get "vehiclesCivMedical"
    } else {
        _civFaction get "vehiclesCivIndustrial"
    };
};
_vehiclePool = _vehiclePool select { typeNAme _x == "STRING" };
```

My thought process is no need to check if "vehiclesCivIndustrial" is nil, because if the loaded factions don't have *any* of those three keys, then really what we have is a faction template issue, not a code issue.

Also, same comment as above wrt the `select` statement.

2025-01-25 15:40 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +                break
So basically what this is doing is checking if the vehicle can load the pallet object (which will have 3 money crate on it), and if not, then whether it can at least load a single money crate.

The `continue` is probably not necessary no. I think it's a holdover from when I was doing other stuff after the if/else statement. The `break` just ensures that if we *can* use the pallet (or any other object, if we add more to the forEach in the future), then we won't waste time checking the rest of the items in the forEach statement and `_supObj` will remain assigned as the pallet (or whatever item we're on). 

There may be a cleaner way to do this. I've dabbled in a lot of different languages for different games and projects (just started with SQF a month or two ago, and learning by reverse engineering lol), but I would call myself somewhere between a novice and amateur haha.

2025-01-25 20:00 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +                break
There's no solution quite like a temporary one

2025-02-07 14:15 UTC, wersal454 commented
> > How much has this been tested? Just curious if you've observed any potential problems with edge cases
> 
> ...not enough. But the testing I _did_ do, I did at least do with Vanilla, RHS, and random 3CB factions. It needs testing to ensure all types still work as normal. The only ones I actually semi-tested while iterating were the money and supplies ones; however, I know of two issues that need solved before merge:
> 
> * [ ]  Wobbling money crates (see my comment in Wersal's repo). I've already tried both `enableSimulation false` and `createSimpleObject` instead of `createVehicle` for the money crates and neither solves the issue.
> * [ ]  I don't think I updated the code that deletes / despawns the objective to delete the money crates. I think it will just delete the pallet they sit on, but this will become a non-issue if we have to just load one crate to fix the first issue.
> 
> Also the money crate could use a new normal and specular map (whatever Arma calls those)

Do wobbling crates actually interact with anything or they are "ghostlike" objects with no physical interactions

If they don't affect anything and just wobble from time to time, I think thats kinda cool)

2025-02-07 14:19 UTC, wersal454 commented
> > > How much has this been tested? Just curious if you've observed any potential problems with edge cases
> > 
> > 
> > ...not enough. But the testing I _did_ do, I did at least do with Vanilla, RHS, and random 3CB factions. It needs testing to ensure all types still work as normal. The only ones I actually semi-tested while iterating were the money and supplies ones; however, I know of two issues that need solved before merge:
> > 
> > * [ ]   Wobbling money crates (see my comment in Wersal's repo). I've already tried both `enableSimulation false` and `createSimpleObject` instead of `createVehicle` for the money crates and neither solves the issue.
> > * [ ]   I don't think I updated the code that deletes / despawns the objective to delete the money crates. I think it will just delete the pallet they sit on, but this will become a non-issue if we have to just load one crate to fix the first issue.
> > 
> > Also the money crate could use a new normal and specular map (whatever Arma calls those)
> 
> Do wobbling crates actually interact with anything or they are "ghostlike" objects with no physical interactions
> 
> If they don't affect anything and just wobble from time to time, I think thats kinda cool)

nuh actually, I think it would be cool if they didn't jitter https://imgur.com/a/wobbling-containers-m3trs1r

with jittering it looks kinda janky, but wobbling effect itself is fine

2025-02-07 16:34 UTC, jwoodruff40 commented
Yeah I can't figure out how to make them not do that. I think we'll just have to get rid of the pallet and use just one money crate for the time being.

Also, I haven't worked on this pr in a bit, but I think the PR might also be a good opportunity to take a crack at fixing community #3417.

2025-02-14 09:53 UTC, wersal454 commented
> Yeah I can't figure out how to make them not do that. I think we'll just have to get rid of the pallet and use just one money crate for the time being.
> 
> Also, I haven't worked on this pr in a bit, but I think the PR might also be a good opportunity to take a crack at fixing community [official-antistasi-community#3433](https://github.com/official-antistasi-community/A3-Antistasi/issues/3433).

I don't it's possible to fix that issue

Maybe it's possible to add an eventhandler in case marker gets flipped that sends convoy to some other outpost?

2025-02-21 14:48 UTC, SilenceIsFatto commented
The wobbling crates is due to a funny engine interaction between a chain of attached objects I believe

If I remember correctly, different objects have different "update" rates when things are attached to them. When you chain multiple objects together that have different rates, this issue occurs (network slowdown can also cause it)

You can't necessarily fix it, it would require the crates and pallet to be one object rather than objects attached to each other

2025-02-24 20:59 UTC, wersal454 commented
bruh I can't
![image](https://github.com/user-attachments/assets/fd74fb3c-fc31-42f2-8aed-756e670e313a)
I've tried commands in vs code and it says "there is no conflicts, bozo"

wtf

2025-02-26 14:31 UTC, SilenceIsFatto commented
@wersal454 If you have [git](https://git-scm.com/downloads) installed (not github), right click in the root A3 repo and click "Open Git Bash here"

Easiest way (for me, at least) is to run:
`git remote add SilenceIsFatto https://github.com/SilenceIsFatto/A3-Antistasi-Ultimate`
`git fetch SilenceIsFatto`
`git checkout patch-50`
`git merge SilenceIsFatto/unstable`

It should then show which files have a merge conflict and you can resolve them in vscode and commit as usual

2025-02-26 14:53 UTC, wersal454 commented
"Merge conflict in A3A/addons/scrt/Stringtable.xml"

Exactly what github tells me

2025-02-26 15:05 UTC, wersal454 commented
jesus

finally

2025-03-06 09:48 UTC, wersal454 commented
> Yeah I can't figure out how to make them not do that. I think we'll just have to get rid of the pallet and use just one money crate for the time being.
> 
> Also, I haven't worked on this pr in a bit, but I think the PR might also be a good opportunity to take a crack at fixing community [official-antistasi-community#3433](https://github.com/official-antistasi-community/A3-Antistasi/issues/3433).

If there isn't a bigger crate that could be retextured, current one will do

2025-03-08 06:37 UTC, jwoodruff40 requested changes
Left some comments to deal with the money crate thing and some other little stuff.

Wth is all this doing in here though?
![wth](https://github.com/user-attachments/assets/b8beebcc-490a-4b3b-85af-98840d3d2053)

Might need to do an interactive rebase on unstable to get rid of all that. Probably an artifact of your repo being forked from community instead of ultimate and a bad merge.

2025-03-08 06:37 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +        } forEach ["Land_Pallet_F", "A3AU_moneyCrate_small_01"];
Remove the extra money crates and pallet. Just use one.

```suggestion
            // * put a supply container in the truck so it can be identified more easily as the objective vehicle
        _supObj = "A3AU_moneyCrate_small_01" createVehicle (position _vehObj);
        
        private _canLoad = [_vehObj, _supObj] call A3A_Logistics_fnc_canLoad;        
        if (_canLoad isEqualType []) then {
            clearMagazineCargoGlobal _supObj;
            clearWeaponCargoGlobal _supObj;
            clearItemCargoGlobal _supObj;
            clearBackpackCargoGlobal _supObj;
            _supObj setDamage 0.75;
            _supObj lockInventory true; // * don't want pesky inquisitive players to know there's not actually anything in here lol
            _supObj call A3A_Logistics_fnc_addLoadAction;
            (_canLoad + [true]) call A3A_Logistics_fnc_load;
        };
```

2025-03-08 06:37 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +            default { (_milFaction get "vehiclesTrucks") };
Can we use the tier war levels configured in Antistasi CBA settings instead of statically setting them to 5/7?
![cba settings](https://github.com/user-attachments/assets/0b75b27f-2338-45f7-90bf-67637b3f16f6)

Also, why are these CBA settings and not params?

2025-03-08 06:37 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +            default { (_milFaction get "vehiclesTrucks") };
same question about the cba settings

2025-03-08 06:37 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +        _vehiclePool = if (_civDisabled) then { _milFaction get "vehiclesMilitiaTrucks" } else { _civFaction get "vehiclesCivIndustrial" } select { typeName _x == "STRING"}; // * convert weighted lis
```suggestion
        _vehiclePool = if (_civDisabled) then { _milFaction get "vehiclesMilitiaTrucks" } else { _civFaction get "vehiclesCivIndustrial" } select { _x isEqualType "" }; // * convert weighted list to normal array
```

2025-03-08 06:37 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +        _vehiclePool = if (_civDisabled) then { _milFaction get "vehiclesMilitiaTrucks" } else { _civFaction getOrDefault ["vehiclesCivMedical", _civFaction get "vehiclesCivIndustrial"] } select { ty
```suggestion
        _vehiclePool = if (_civDisabled) then { _milFaction get "vehiclesMilitiaTrucks" } else { _civFaction getOrDefault ["vehiclesCivMedical", _civFaction get "vehiclesCivIndustrial"] } select { _x isEqualType "" }; // * convert weighted list to normal array
```

2025-03-08 06:37 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +    default { (_milFaction get "vehiclesLightArmed") };
same question about the cba settings

2025-03-08 06:37 UTC, jwoodruff40 commented on A3A/addons/core/CfgVehicles.hpp
> +
These aren't used anymore 
```suggestion
```

2025-03-08 06:37 UTC, jwoodruff40 commented on A3A/addons/core/Pictures/Items/supplydrop_medical_01_co.paa
delete this

2025-03-08 06:37 UTC, jwoodruff40 commented on A3A/addons/core/Pictures/Items/supplydrop_medical_02_co.paa
delete this too

2025-03-09 14:08 UTC, SilenceIsFatto commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +            default { (_milFaction get "vehiclesTrucks") };
Because the params don't have a native slider control

2025-03-09 14:38 UTC, jwoodruff40 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +            default { (_milFaction get "vehiclesTrucks") };
Hmm, I can probably add sliders to certain params instead of LBs. At least to see if it feels better. It could make it feel more disjointed though, one way to find out.

2025-03-10 11:04 UTC, wersal454 commented on A3A/addons/core/functions/Missions/fn_convoy.sqf
> +            default { (_milFaction get "vehiclesTrucks") };
I don't think that this should used for that, those sliders are for unit types purely, vehicle stuff is unaffected iIrc

Also, other missions also don't use them or affected by them (again iIrc)

2025-03-14 23:34 UTC, SilenceIsFatto commented
Continued in #524

2025-03-14 23:34 UTC, closed without merging